### PR TITLE
Prefix all paths in proxito urls

### PR DESCRIPTION
**Pull request by ericholscher**

### CODE REVIEW

**Review by stsewd — COMMENTED** [review]
These are paths, not re_paths.

**Review by stsewd — COMMENTED** [review]
What's the problem you are solving? I think we are good using pure paths instead of re_paths here.

**Comment by ericholscher** [comment]
These will match other URLS than aren't the ones we want, right?

**Comment by stsewd** [comment]
No, path is an exact match.

**Pull request closed without merging**
