### PR TITLE
Always show the raw compilation for debugging purpose

### PR DESCRIPTION
**Pull request by alkino**
Let show the compilation log, it's easier to find information inside.

### CODE REVIEW

**Review by stsewd — COMMENTED** [review]
Not sure about this, the full log being shown at the end makes sense to me. Having it show early could be misleading that the build finished.

**Comment by alkino** [comment]
My problem today is my builds looking stuck on `cat conf.py` for 10 minutes!
https://readthedocs.org/projects/coreneuron/builds/12808875/

In fact it's running something behind the scene.
And showing the raw log doesn't help because it shows only finished commands.

I think the log should be better to help user making things.

**Comment by alkino** [comment]
Wait for #7005

**Comment by stsewd** [comment]
> My problem today is my builds looking stuck on cat conf.py for 10 minutes!

That's because we show the log only when the current command is finished, in this case, the command being executed that lasted 10 min was the `sphinx` command, the raw log would have shown the same step as you see in the normal log. See https://github.com/readthedocs/readthedocs.org/issues/4288

**Pull request closed without merging**
