### PR TITLE
Implemented orjson

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Related https://github.com/readthedocs/readthedocs.org/issues/6130. I think library is fastest.

Writing separate PR for https://github.com/readthedocs/readthedocs.org/issues/6130#issuecomment-528711975.

### CODE REVIEW

**Comment by humitos** [comment]
Hi @tapaswenipathak. Thanks for your PR!

I saw that @dojutsu-user was suggesting using `orjson`.

Do we have some benchmark about this? Is it possible to know if this will really  have an impact on time?

Also, Eric mentioned that probably the issue is on the HTML parsing and the usage of PyQuery. Maybe that's another place to attack this issue. Although, it's hard to tell what's the best path to follow without some previous benchmarks.

**Comment by dojutsu-user** [comment]
@humitos 
`orjson` documentation does provide some benchmarks: https://github.com/ijl/orjson#twitterjson-serialization
Also, I am testing [html5_parser](https://github.com/kovidgoyal/html5-parser) for faster parsing.

**Comment by tapaswenipathak** [comment]
@humitos: There are lot of blogs available, `orjson` is fastest, no need for extra research, see - https://pythonspeed.com/articles/faster-json-library/.

@dojutsu-user: Are you writing a PR or should I write?

**Comment by tapaswenipathak** [comment]
folks: Uh, I read wrong! I am writing orjson. I read rapidjson is fastest.

**Comment by dojutsu-user** [comment]
Hi @tapaswenipathak 
Yes, I am working on a separate PR.

**Comment by dojutsu-user** [comment]
Hi @tapaswenipathak 
I have opened #6160 which also contains the work in this PR with other things.
I am closing this PR.
We can target anything left in this PR in #6160.

Thanks for your contribution. :+1: :100:

**Comment by tapaswenipathak** [comment]
Hello, assign yourself the ticket if you are writing a PR. The open
source etiquettes is never closing a PR solving a ticket; being a
maintainer keeping yourself well behaved is necessary, early you
implement the better, glad you were willing writing PR from your end.


On Tue, Sep 10, 2019 at 5:30 PM Vaibhav Gupta <notifications@github.com> wrote:
>
> Hi @tapaswenipathak
> I have opened #6160 which also contains the work in this PR with other things.
> I am closing this PR.
> We can target anything left in this PR in #6160.
>
> Thanks for your contribution.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
Tapasweni

**Pull request closed without merging**
