### PR TITLE
Docs: Upgrade Sphinx & sphinx_rtd_theme

### PR DESCRIPTION
**Pull request by ericholscher**
This basically removes all pins from ``docs.in``,
and lets it resolve the properly fancy versions :)

### CODE REVIEW

**Review by humitos — APPROVED** [review]
👏

**Comment by benjaoming** [comment]
harvesting the good stuff :100:

**Comment by ericholscher** [comment]
It's still pinning us to Sphinx 5.3, which I'm guessing is the upper limit on one of the dependencies? But baby steps :)

**Comment by benjaoming** [comment]
Yes, it's because of sphinx-design IIRC

**Pull request merged**
