### PR TITLE
Fix migration

### PR DESCRIPTION
**Pull request by stsewd**
Both migrations are named 0096.

### CODE REVIEW

**Comment by stsewd** [comment]
I'm going to just merge this, so tests aren't broken.

**Comment by benjaoming** [comment]
There's another candidate for migration linting! We were talking earlier about trying to avoid adding non-nullable migrations for new fields.

**Comment by benjaoming** [comment]
> This actually can be fixed by requiring PRs to be updated before merging

You might be able to spot the issue then, but there's no guarantee... TBH, I might be inclined to merge the latest main, see that the tests pass and then _not_ notice that there are two 0096_* files :)

**Comment by stsewd** [comment]
Tests will error if there are duplicades, we don't need to manually check them

**Comment by benjaoming** [comment]
In that case, it's all good :+1:

**Pull request merged**
