### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by miketheman**
Refs: readthedocs/readthedocs-docker-images#198

### CODE REVIEW

**Comment by humitos** [comment]
I think we can probably wait a little until Python 3.12 is released and update all of them together.

**Comment by ThiefMaster** [comment]
Python 3.12 is out now, also for 3.11 there's 3.11.6 available.

**Comment by miketheman** [comment]
@humitos This and the other PR have been updated for 3.11.6 and 3.12.0

**Review by humitos — APPROVED** [review]
Looks good to me!

We can merge it once https://app.circleci.com/pipelines/github/readthedocs/readthedocs-docker-images/273/workflows/362fb08e-f5c5-4f66-bf64-6b803cdf8aa4/jobs/477 completes.

**Comment by stsewd** [comment]
We may want to merge https://github.com/readthedocs/readthedocs.org/pull/10808, it's a more complete update.

**Pull request closed without merging**
