### PR TITLE
Add azurite --loose option

### PR DESCRIPTION
**Pull request by agjohnson**
I was getting 5xx errors from azurite every other load of a static asset
file. I found this issue and added a fix that was mentioned:
https://github.com/Azure/Azurite/issues/337

I can not reccomend this fix and I did not try to spend any time
understanding Azurite.

### CODE REVIEW

**Comment by agjohnson** [comment]
Also, to clarify, the `--loose` option did resolve the problem I was seeing. I'm able to consistently reload the assets now. I'd be fine pinning the Azurite image or adding the `--loose` option. I don't think it makes a whole lot of sense to spend time figuring out Azurite as we don't use it anywhere outside local development.

**Comment by humitos** [comment]
What's the hash of your azurite image?

**Comment by humitos** [comment]
I re-downloaded the azurite docker image and it works now :man_shrugging:

**Comment by agjohnson** [comment]
My azurite is:

```
mcr.microsoft.com/azure-storage/azurite         latest              741b0142b740        10 days ago         292MB
```

**Pull request merged**
