### PR TITLE
Add information on using graph based redirects

### PR DESCRIPTION
**Pull request by Daltz333**

### CODE REVIEW

**Comment by Daltz333** [comment]
I can reword or make more detailed if appropriate.

**Comment by humitos** [comment]
> It would be nice to have a "popular extensions" page on ReadtheDocs. I can contribute to this and get it started if approved.

I started this project some time ago that you may be interested in contributing https://sphinx-extensions.readthedocs.io/en/latest/

**Comment by astrojuanlu** [comment]
(I amend myself: https://sphinx-extensions.readthedocs.io/en/latest/ is not linked from the official tutorial - that's my fault, it probably should!)

**Comment by Daltz333** [comment]
Will do

**Pull request closed without merging**
