### PR TITLE
Auto build new tags when pushed.

### PR DESCRIPTION
**Pull request by ericholscher**
Add tests for this and the stable version code.

### CODE REVIEW

**Comment by rmzelle** [comment]
Is this code also supposed to create the "stable" version if it doesn't yet exist?

I just pushed my first tags to my repo, and while they show up at https://readthedocs.org/projects/citation-style-language/versions/, I don't see an option to build the "stable" version for one of these tags. I guess it might show up once I make a new commit, but ideally that shouldn't be necessary, right?

**Comment by rmzelle** [comment]
I just pushed a commit to my repo, and I still don't have the option to build the "stable" branch.

**Comment by gregmuellegger** [comment]
@rmzelle It seems like the stable version appeared for your project, right? Did you do anything special about it or did it just work?

**Comment by rmzelle** [comment]
I think switching to another GitHub target repo and back did the trick, but I'm not a 100% sure. It was definitely broken before.

**Pull request merged**
