### PR TITLE
Notifications: render `Organization` notifications on details page

### PR DESCRIPTION
**Pull request by humitos**
This work was missed when implementing the new notification system.

Screenshot_2024-01-10_10-56-20

Related https://github.com/readthedocs/ext-theme/issues/260

### CODE REVIEW

**Comment by agjohnson** [comment]
Also, I'm guessing you may need to update the commercial templates with the missing logic.

**Review by agjohnson — APPROVED** [review]

**Comment by humitos** [comment]
> Also, I'm guessing you may need to update the commercial templates with the missing logic.

I'm not sure to follow you here. I updated community templates for the old dashboard, which are used on commercial instance. In fact, the screenshot I uploaded in the description is from my commercial development instance. Am I missing something here?

**Comment by agjohnson** [comment]
@humitos Gotcha, it wasn't clear to me that screenshot was the updated notification.

I don't recall what we've overridden in corporate at this point, I haven't touched these templates for a while. Organization notifications seem good, but I would still look through these templates to ensure all the logic is replicated there. Especially for any templates that override community or do not inherit from community.

The base template doesn't inherit and seems to be missing the loops around `notifications` on corporate for example: https://github.com/readthedocs/readthedocs-corporate/blob/a7343911b82220c3d8c2d9348cd4b9e009868e32/readthedocsinc/corporate/templates/base.html#L61-L81

**Comment by humitos** [comment]
Cool! I opened https://github.com/readthedocs/readthedocs-corporate/issues/1709 to keep track of this 👍🏼

**Pull request merged**
