### PR TITLE
CSS Optimization

### PR DESCRIPTION
**Pull request by AqeelAT**
I was reviewing core.css to prime it for dark mode and found multiple redundancies. Fixed now. The next step is to add a dark mode theme based on prefers-color-scheme.

### CODE REVIEW

**Comment by humitos** [comment]
Hi @AqeelAT! We are working on a complete re-work of our templates. So, I'm not sure how these CSS optimization could be merged with the work we already started.

Besides, could you explain a little more what you have done? There are 2.5k lines changed in this PR, which is super hard to review.

**Comment by AqeelAT** [comment]
Is there a way to join in the re-work? My little sister and I are already working on choosing the colors for dark mode. You can check our progress [here](https://github.com/AqeelAT/readthedocs.org/tree/darkmode/media/css). We're just starting, but we would love to combine our efforts with yours if you're already working on the same issue.

### For this pull request:
Most of the lines are just reformatted code.
but basically, there were multiple instances of:
```css
.someClass {
  border: 0;
  border: something else;
}
```
I also:

1. fixed incorrect CSS rules such as `text-color`.
2. removed unneeded vendor prefixes based on guidance from http://shouldiprefix.com/
3. added a comment to point out that one instance of `display: auto` should be fixed because the rule doesn't exist, but didn't know how to fix it.

**Comment by agjohnson** [comment]
HI @AqeelAT! I'm glad to see someone interested in helping out on the design side!

I'm managing the new template project, but it's not a great place to contribute currently. Development is heavy and moving fast right now, and contributions will slow down full-time development efforts. I'm hoping to keep the project on schedule and to have templates in a place where general contributions will be helpful within the next month. I can be in touch when we get closer. Currently, places in our code that are not great places to contribute are: CSS, any JavaScript that manipulates our UI, and all of our templates.

As @humitos hinted at, the new templates will throw out *all* existing CSS, *all* existing templates, and so far we only have maybe 100 lines of minor CSS code for customizations on top of SemanticUI -- we're looking to avoid maintaining CSS however possible and SUI is doing a great job of doing all of our heavy lifting. So, very unfortunately, we likely won't be able to use your efforts here, as we're close to a freeze on these pieces and introducing major changes will conflict with replacing the CSS/templates entirely.

As for a feature for dark mode, we likely would not accept a feature like this, though I believe we've discussed this briefly in the past. The team doesn't have a lot of strength maintaining the design of the site already, let alone 2 designs.

If you have interest in working with CSS, I might suggest you hop on over to https://github.com/readthedocs/sphinx_rtd_theme. This is maybe a better place for you to contribute at the moment. The best areas to contribute there are in QA of changes -- across versions of Sphinx and Python -- and in helping triage and debug issues. To avoid any wasted efforts, it is always best to raise potential new features/changes on the issue tracker first, to involve core team members from the start.

So, very long story short, we really appreciate the effort, but it's probably best to close this PR.

**Comment by AqeelAT** [comment]
Got it. Please let me know if there's anything I can help with. Closing the PR.

**Comment by AqeelAT** [comment]
@agjohnson any updates on the project?

**Pull request closed without merging**
