### PR TITLE
Update mkdocs default version

### PR DESCRIPTION
**Pull request by stsewd**
Everything looking good in local testing.
The changelog doesn't mention anything breaking.

ref https://github.com/readthedocs/readthedocs.org/issues/7539

### CODE REVIEW

**Review by Mailaender — APPROVED** [review]

**Review by Mailaender — CHANGES_REQUESTED** [review]
Seems still broken:

before: https://docs.openra.net/en/latest/release/lua/
after: https://openhv.readthedocs.io/en/latest/release/lua/

Additionally the table of contents is partly gone.

**Comment by stsewd** [comment]
@Mailaender if you are already using the latest version of mkdocs you should report those problems to mkdocs, this isn't related to rtd.

**Review by humitos — COMMENTED** [review]
Won't this affect to _all the builds_ that are not pinning mkdocs? I think what we want here is a feature flag that uses `mkdocs<1.2` only for new projects.

I don't think we have a plan to update build dependencies that we install by default, but if we don't, we should so we apply it every time we need it. Like this case.

**Comment by stsewd** [comment]
> Won't this affect to all the builds that are not pinning mkdocs? I think what we want here is a feature flag that uses mkdocs<1.2 only for new projects.

Yes, but this update isn't going to break the builds. Is just a minor update.

**Comment by ericholscher** [comment]
This removes python 3 support, along with a number of other large changes: https://www.mkdocs.org/about/release-notes/#other-changes-and-additions-to-version-11 -- this will *definitely* break things for people.

**Comment by Mailaender** [comment]
They really shouldn't have snug that into a point release.

**Comment by stsewd** [comment]
I think we can add this after https://github.com/readthedocs/readthedocs.org/pull/7524 is merged

**Pull request closed without merging**
