### PR TITLE
Add Python 3.12 to allowed Python versions

### PR DESCRIPTION
**Pull request by A5rocks**
Hopefully this is the correct flow -- the comments above say to run `scripts/compile_version_upload.sh` but I'm not exactly sure how I do that.

If this needs to be done by someone working at RTD, feel free to close this. I was going to just make an issue but it looked easy enough to do this sort of bump!

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--10808.org.readthedocs.build/en/10808/

- Developer's documentation (`dev`): https://dev--10808.org.readthedocs.build/en/10808/

### CODE REVIEW

**Review by stsewd — APPROVED** [review]
Thanks!

**Comment by stsewd** [comment]
> Hopefully this is the correct flow -- the comments above say to run scripts/compile_version_upload.sh but I'm not exactly sure how I do that.

Updating and uploading the new versions was done in https://github.com/readthedocs/readthedocs-docker-images/pull/198.

**Comment by humitos** [comment]
We can merge this PR once this CircleCI job has ran successfully: https://app.circleci.com/pipelines/github/readthedocs/readthedocs-docker-images/273/workflows/53d89e70-c7d6-445a-afcf-0d7cdaea124f/jobs/479

**Comment by humitos** [comment]
The sync to S3 passed. I'm merging...

**Comment by ThiefMaster** [comment]
Is it already available? At least on https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python I don't see 3.12 yet

**Comment by humitos** [comment]
@ThiefMaster no, it will be available after next deploy on Tuesday.

**Pull request merged**
