### PR TITLE
Domain: remove retry task

### PR DESCRIPTION
**Pull request by stsewd**
This is going to be a periodic task now (on rtd-ext). We can remove it after we see how the periodic tasks work

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
Looks good! I'll set to blocking on testing out the tasks more.

**Comment by ericholscher** [comment]
Is this unblocked now?

**Comment by stsewd** [comment]
I'd say yes, we need to remove the call to this task in .com as well, I'll make a PR for that as well.

**Comment by stsewd** [comment]
Superseded by https://github.com/readthedocs/readthedocs.org/pull/7763/

**Pull request closed without merging**
