### PR TITLE
Moving READTHEDOCS application settings to RTD prefix for docker only 

### LINKED ISSUE #5586: Move our application settings to a READTHEDOCS prefix on our settings
We have a number of settings that don't have a `READTHEDOCS` prefix and this makes our settings hard to find. The core team would like to consolidate our application settings to use a prefix so that they are easier to find and search for in our code.

This is related to how we would like to remove the use of getattr usage in #2140. It's probably either blocked or at least related.

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
fixes #5586

### CODE REVIEW

**Comment by dojutsu-user** [comment]
Hi @Iamshankhadeep 
I noticed that you close the previous PR and make another PR if any changes are required.
This is generally not how it's done.
I would recommend you to read this article -- https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github -- to make yourself familiar with the correct workflow.

Also, Pull request from `master` branch are generally discouraged.

**Comment by Iamshankhadeep** [comment]
@dojutsu-user thanks I will be sure to update the required things.

**Comment by Iamshankhadeep** [comment]
@humitos I  think I made a mistake by deleting the forked repo of readthedocs from where this PR was opened. I followed @dojutsu-user's instruction and deleted the previous repo and froked again and also added a new branch specific for this work. I think I need to close this PR and open new PR  and from there If needed I can rebase it.Sorry, a beginner in this open source contribution. If you say to close this PR and open a new one I will be more than  happy to do so.

**Comment by dojutsu-user** [comment]
@Iamshankhadeep 
I am closing this PR since the forked repo is deleted.

**Pull request closed without merging**
