### PR TITLE
Fix tasks

### PR DESCRIPTION
**Pull request by stsewd**
This task was deleted from common

Closes https://github.com/readthedocs/readthedocs.org/issues/8369

### CODE REVIEW

**Comment by ericholscher** [comment]
Is there a way to write a test for this? Perhaps even just importing the file?

**Comment by stsewd** [comment]
I think maybe the linter can tell if we import the tasks directly (`from foo import task_name` instead of `import foo`), let me try, if not I can try just importing the file

**Comment by astrojuanlu** [comment]
I confirm that this closes #8369.

**Review by humitos — APPROVED** [review]
👍🏼

**Comment by humitos** [comment]
I'm merging this to avoid having the development instance broken. We can add the tests in another PR.

**Pull request merged**
