### PR TITLE
Add proper div names on our ad placements

### PR DESCRIPTION
**Pull request by ericholscher**
This will be deprecated here soon,
but for now this will make that data more clean.

### CODE REVIEW

**Review by humitos — COMMENTED** [review]
I'm not sure if I have the context about this change. I guess we just want human-readable names here but don't really know how/where they are used. We may want to keep the postfix random number as it was, tho: `rtd-explicit-2918`.

**Comment by ericholscher** [comment]
Why do we want the random number?

**Comment by humitos** [comment]
I don't have the answer to that, but I suppose that it was added for some reason :sweat_smile:, obfuscate or avoid id collisions, perhaps?

**Comment by ericholscher** [comment]
I talked with David, and these were originally done for ad blocking, but it didn't work :) So I think they are safe to remove, tho this code will be removed in a couple weeks anyway, so I'm fine if this doesn't ship.

**Review by humitos — APPROVED** [review]
OK!

**Pull request merged**
