### PR TITLE
Try to fix annotated tags

### LINKED ISSUE #6932: "Edit on Github" link broken by annotated tag
## Details

* Read the Docs project URL: https://osmnx.readthedocs.io/en/stable/
* Build URL (if applicable): https://github.com/gboeing/osmnx/
* Read the Docs username (if applicable): gboeing

## Expected Result

The "edit on Github" link at the top-right of the stable docs should point to the latest release.

## Actual Result

The [link](https://github.com/gboeing/osmnx/blob/685b9d0c7aac56ccd0ef3259515aa8404d254056/docs/source/index.rst) is broken. The problem seems to be how readthedocs uses the annotated tag that denotes the release. The link generated by readthedocs points to checksum `685b9d0` which is just an annotated tag that points to commit `902461a`. You can see this here:

```
$ git show 685b9d0c7aac56ccd0ef3259515aa8404d254056
tag v0.12
Tagger: gboeing <boeing@usc.edu>
Date:   Fri Apr 10 11:09:25 2020 -0700

v0.12

commit 902461ab8eb668732fa025c670057662fdd22039 (tag: v0.12)
Merge: bb1ef92 5ec6c2b
Author: Geoff Boeing <gboeing@users.noreply.github.com>
Date:   Fri Apr 10 11:06:56 2020 -0700

    Merge pull request #420 from gboeing/release
    
    v0.12 release
```

The [link](https://github.com/gboeing/osmnx/blob/685b9d0c7aac56ccd0ef3259515aa8404d254056/docs/source/index.rst) that readthedocs generates points to the annotated tag checksum, but that just leads you to a 404 page because you cannot browse at that point on Github. You [can](https://github.com/gboeing/osmnx/blob/902461ab8eb668732fa025c670057662fdd22039/docs/source/index.rst) only browse at the commit that the annotated tag points to. 

Related info from the [git docs](https://git-scm.com/book/en/v2/Git-Basics-Tagging):

> Git supports two types of tags: lightweight and annotated.
> 
> A lightweight tag is very much like a branch that doesn’t change — it’s just a pointer to a specific commit.
> 
> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information

### PR DESCRIPTION
**Pull request by stsewd**
Maybe fixes #6932

### CODE REVIEW

**Comment by ericholscher** [comment]
I think I'd like to just revert the original -- this keeps getting more complex, and I'm not sure this is actually valuable? How much faster is this than the original code?

**Comment by stsewd** [comment]
@ericholscher the original code opens a file and iterates over till it finds a match for each tag. The complexity grows in `O(n^2)` (n is the number of tags), and opening files `n^2` times as well.

https://github.com/gitpython-developers/GitPython/blob/e236853b14795edec3f09c50ce4bb0c4efad6176/git/refs/symbolic.py#L125-L135

https://github.com/gitpython-developers/GitPython/blob/e236853b14795edec3f09c50ce4bb0c4efad6176/git/refs/symbolic.py#L85-L123

This consumes a lot of build time for projects with a lot of tags (and it makes syncs slow too), not sure if the new builders can handle this better.

**Comment by ericholscher** [comment]
OK, I guess it makes sense to try and optimize this then 👍

**Comment by stsewd** [comment]
Tested this locally, built time is almost the same as before for projects with thousands of tags (< 5 min)

**Pull request merged**
