### PR TITLE
HTMLFile: remove slug field

### PR DESCRIPTION
**Pull request by stsewd**
Continuation of https://github.com/readthedocs/readthedocs.org/pull/7228

### CODE REVIEW

**Comment by stsewd** [comment]
I'm not sure if django runs all migrations at once or one by one (without committing), but in any case is safe if we merge this after the next deploy

**Comment by stsewd** [comment]
The migration needs to be updated before merging

**Comment by ericholscher** [comment]
Will this cause issues on deploy, if the code is still trying to set this field and it's gone from the DB?

**Comment by stsewd** [comment]
@ericholscher only tests were setting that value, we don't have code setting it.

https://github.com/readthedocs/readthedocs.org/blob/98463241148f86dd37cc38e1102926ca2f976969/readthedocs/projects/tasks.py#L1551-L1559

The field is already nullable.

**Comment by ericholscher** [comment]
Right, but the code will still set `slug=None` on save, and postgres will error out like "`slug` doesn't exist!", right?

**Comment by stsewd** [comment]
oh, I get what you are saying. We can't split this, as the linter will fail because the migration isn't there. What we should do is first deploy the code and after that run the migration, as the field is nullable we won't have any errors before the migration is run. Currently, we are running migrations before the code is deployed, if this is merged I can create a note to run this migration after.

**Comment by ericholscher** [comment]
Yea, I guess thats something to address with the linter at some point, but running the migration late should be fine.

**Review by ericholscher — APPROVED** [review]

**Pull request merged**
