### PR TITLE
Docs: test new theme version/language selector

### PR DESCRIPTION
**Pull request by humitos**
Reference:

* https://github.com/readthedocs/sphinx_rtd_theme/pull/1601

### CODE REVIEW

**Comment by ericholscher** [comment]
Are we wanting to ship this now, or are we just testing the PR builds for now

**Comment by humitos** [comment]
I created this PR as a way to show the work we are doing on the theme. I'd appreciate a review on the theme PR first. After that, we can merge this one and continue iterating.

**Comment by humitos** [comment]
It currently looks like this

Peek 2024-09-19 12-09

**Comment by humitos** [comment]
Superseded by https://github.com/readthedocs/readthedocs.org/pull/11611

**Pull request closed without merging**
