### PR TITLE
DONT_INSTALL_DOCUTILS feature flag

### LINKED ISSUE #7275: Use up to date version of docutils by default
We are currently using `docutils==0.14` by default, but `docutils==0.16` is out as of 2020-01. There are some inconsistencies in reST syntax because of the difference. Also, docutils doesn't version their docs :( This means an author using examples from the docutils docs might try to use features from 0.16. A failure case here would mean Sphinx skips the content.

### PR DESCRIPTION
**Pull request by humitos**
Allow people to ~~install latest release of docutils (currently, 0.16)~~ not install `docutils` at all

Closes #7275

### CODE REVIEW

**Comment by stsewd** [comment]
I think we can just remove that dependency, and leave it to sphinx to decide the version

https://github.com/sphinx-doc/sphinx/blob/cbc16eb384a0fc6181a4543c34977e794cae231d/setup.py#L26

**Comment by humitos** [comment]
That makes sense to me. I wonder why we had it originally. Maybe older versions of Sphinx does not have this requirement?

This requirement has been there "forever". This is the original commit where that file is created from `projects/tasks.py`: https://github.com/readthedocs/readthedocs.org/commit/a6f209473933637816e11d730dcf5c65641a0865

Yeah, it seems it was added to support old Sphinx versions: https://github.com/readthedocs/readthedocs.org/commit/37ea03ab62c8bed6c770de94f413459c77a9b85a

**Comment by humitos** [comment]
Using a feature flag is the safest and immediate change to do :smile: --we can try removing the dependency with another feature flag to cover ourselves in a different PR, I suppose. Thoughts?

**Comment by stsewd** [comment]
Looks like sphinx includes docutils since the beginning https://github.com/sphinx-doc/sphinx/blob/be6aa3940e2efc0a9372072ea4e6ae4525f0a2cc/setup.py#L47

So, I guess the problem was with a breaking change in docutils and incompatible with sphinx or something like that.

**Comment by agjohnson** [comment]
I'd be fine skipping to a feature flag that doesn't install docutils at all. It seems like it was likely a temporary concern anyways.

**Comment by humitos** [comment]
I changed the meaning of the flag. Please, re-review his.

**Pull request merged**
