### PR TITLE
Subscriptions: Set organization name in Stripe

### PR DESCRIPTION
**Pull request by ericholscher**
This is useful in lots of places.

### CODE REVIEW

**Review by humitos — APPROVED** [review]
This looks good to me. I'm pinging @stsewd because I remember him already doing this but maybe his PR didn't get merged yet?

**Comment by stsewd** [comment]
> This looks good to me. I'm pinging @stsewd because I remember him already doing this but maybe his PR didn't get merged yet?

mine was to update the subs description, not the name.

**Comment by ericholscher** [comment]
The name is used in a lot of places in Stripe, and would definitely be useful to have.

**Comment by ericholscher** [comment]
Docs failure is unrelated.

**Pull request merged**
