### PR TITLE
Docs: Remove outdated and misleading Poetry guide

### PR DESCRIPTION
**Pull request by juantocamidokura**
Fixes https://github.com/readthedocs/readthedocs.org/issues/9771

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--9794.org.readthedocs.build/en/9794/

- Developer's documentation (`dev`): https://dev--9794.org.readthedocs.build/en/9794/

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
LGTM :+1:

**Comment by ericholscher** [comment]
We should likely update this guide, or at least put in a redirect to some content that we have around this. It's a common topic, so where should we be sending people who need this type of content?

**Comment by benjaoming** [comment]
@ericholscher how about we do a redirect to the configuration example? https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry (secondary question: are redirects with anchors supported?)

**Comment by benjaoming** [comment]
@ericholscher in case you agree that we can do this without a placeholder, the redirect is ready :+1:

**Comment by ericholscher** [comment]
That redirect works 👍

**Comment by benjaoming** [comment]
Redirect tested :+1: 

https://docs.readthedocs.io/en/latest/guides/poetry.html

**Pull request merged**
