### PR TITLE
ImportedFile: remove slug 1/2

### PR DESCRIPTION
**Pull request by stsewd**
We are not using this field,
actually we are not even setting it.

https://github.com/readthedocs/readthedocs.org/blob/98463241148f86dd37cc38e1102926ca2f976969/readthedocs/projects/tasks.py#L1551-L1559

In production all files have that field empty.

I'm making this a two-step operation, so we don't have downtime.

### CODE REVIEW

**Comment by stsewd** [comment]
The migration needs to be updated after https://github.com/readthedocs/readthedocs.org/pull/7274/ is merged

**Review by humitos — COMMENTED** [review]
If we are not setting it when creating the object, it wasn't `null=True` and it has not `default=` value, how it was working?

**Comment by stsewd** [comment]
@humitos who knows :man_shrugging:

**Comment by humitos** [comment]
Weird...

```
                                        Table "public.projects_importedfile"
    Column     |           Type           | Collation | Nullable |                      Default                      
---------------+--------------------------+-----------+----------+---------------------------------------------------
...
 slug          | character varying(50)    |           | not null |
...
```

`slug` is being set to `''` for some reason. We must be doing something somewhere else.

**Review by ericholscher — APPROVED** [review]
Makes sense to me -- is part 2 of this work tracked somewhere?

**Comment by stsewd** [comment]
> is part 2 of this work tracked somewhere?

Part two is just to the actual deletion of the field, I was about to make that PR after this one was merged

**Pull request merged**
