### PR TITLE
Add test settings file for proxito

### PR DESCRIPTION
**Pull request by stsewd**
This is needed to allow us to run tests with the proxito settings in
.com (and probably in .org too)

### CODE REVIEW

**Comment by stsewd** [comment]
@humitos looks like we are not using any file from here for the production settings, neither on .org or .com. We should use the base settings from here after it's merged so we don't duplicate them.

**Comment by ericholscher** [comment]
We should merge this after fixing the conflict.

**Comment by davidfischer** [comment]
After this was merged, in my local environment it seems to create an empty `readthedocs/settings/proxito.py`. I think it's the result of [this](https://github.com/readthedocs/readthedocs.org/blob/b4dcd2d4e3534afaf06ace7b99130a738467a0b7/docker-compose.override.yml#L38). This causes proxito to fail to start due to the `SECRET_KEY` not being set.

**Comment by humitos** [comment]
Yes. This breaks the local environment. I think it's better to have everything related to tests inside the `tests/` directory, so they are isolated. I propose to move this to `readthedocs/proxito/tests/settings`.

**Comment by humitos** [comment]
I open a PR with a fix for this at #6703 without changing the structure.

**Pull request merged**
