### PR TITLE
Docker: install requirements from local changes

### PR DESCRIPTION
**Pull request by stsewd**
This requires https://github.com/readthedocs/common/pull/68

### CODE REVIEW

**Review by humitos — CHANGES_REQUESTED** [review]
I don't like this change, and I'd prefer if we don't merge it. With this, we will end up with docker images that have random requirements installed on them instead of the latest from our master branches. I used `curl` on purpose here for this reason.

If you want to temporarily install requirements from the current branch you are working on, you should use `entrypoints/common.sh` script and add `pip install -r requirements.txt` to match the requirements of the branch you are working on.

**Comment by stsewd** [comment]
What's the use case if you have local changes in the requirements files and don't want to install them? You'll be also installing them only if you rebuild the images.

**Comment by stsewd** [comment]
And btw, using the scripts in common won't get you a clean environment, as some dependencies may be removed in the new requirements, so I don't think that's a valid reason to block this change.

**Comment by humitos** [comment]
> What's the use case if you have local changes in the requirements files and don't want to install them? You'll be also installing them only if you rebuild the images.

My idea behind using `curl` was to all have the same images, no matter the status of your local copy. Then if you need any modification to the image, you can use the `common.sh` script or similar flow to install/update/delete packages or others. I think this avoid mistakes of having Docker images with corrupted data.

> And btw, using the scripts in common won't get you a clean environment, as some dependencies may be removed in the new requirements, so I don't think that's a valid reason to block this change.

This is a good point.

Overall, I thought more about this and I don't think it's too important really. Yesterday I saw it more dangerous/error prone than it is in reality.

**Review by humitos — APPROVED** [review]

**Comment by humitos** [comment]
> This requires [readthedocs/common#68](https://github.com/readthedocs/common/pull/68)

Shouldn't this PR updates common/ submodule to point to that particular commit?

**Pull request merged**
