### PR TITLE
Update pytest packages

### PR DESCRIPTION
**Pull request by stsewd**
New version of pytest and friends fix the problems that we have

### CODE REVIEW

**Comment by stsewd** [comment]
Unrelated failure, something changed in master, fixing it in a few minutes

**Comment by stsewd** [comment]
For some reason tests are failing in the .com CI :)

**Comment by humitos** [comment]
@stsewd I re-triggered the tests on CI, but the last time they passed.

Also, did you test that this does not make Corporate to break? In that case, we can merge this PR.

**Comment by stsewd** [comment]
There is a PR in corporate, that's the blocker.

**Comment by stsewd** [comment]
Closing in favor of https://github.com/readthedocs/readthedocs.org/pull/6233/

**Pull request closed without merging**
