### PR TITLE
Version should be in quotes

### PR DESCRIPTION
**Pull request by askpatrickw**
Just like the one in this repo. ;-)

### CODE REVIEW

**Comment by humitos** [comment]
Hi! Thanks for these changes.

I noted these changes are for the V1 of the config file, which in not sure if works with the Python version as string. cc @stsewd 

Actually, I'd say we should remove everything related to config V1 from our documentation to avoid confusion and start deprecating it. @ericholscher what do you think?

**Comment by askpatrickw** [comment]
Sorry, I missed that it was a versioned format. In the V2 docs, I think you still need to add the quotes.

**Comment by agjohnson** [comment]
We discussed removal and options a bit at #8648

**Comment by humitos** [comment]
> Of course the next question is, why does it have to be in quotes and why doesn't build.os? ;-)

This is to avoid float numbers confusion on Python version. If you use `python.version: 3.10` in the config file, that will be interpreted as `3.1`, but `"3.10"` will be `3.10`. `build.os` does not have this problem.

**Comment by askpatrickw** [comment]
Doesn't sound like this PR is going to move forward, closing.

**Pull request closed without merging**
