### PR TITLE
Requirements: update django-allauth

### PR DESCRIPTION
**Pull request by stsewd**
### 0.43.0

> In previous versions, the allauth app included a base.html template. This
> template could conflict with an equally named template at project level.
> Therefore, base.html has now been moved to account/base.html -- you will need
> to check your templates and likely override account/base.html within your
> project.

We include our own base.html template,
in order to make the allauth templates
use our base template I have added an account/base.html
file that just extends from base.html.

### 0.44.0

> The certificate key part of the SOCIALACCOUNT_PROVIDERS configuration has been
> renamed to certificate_key. This is done to prevent the key from being
> displayed without being masked in Django debug pages.

We don't use that field, nor we access it from our application.

### 0.47.0

> Added a new setting SOCIALACCOUNT_LOGIN_ON_GET that controls whether or not the
> endpoints for initiating a social login (for example,
> "/accounts/google/login/") require a POST request to initiate the handshake. As
> requiring a POST is more secure, the default of this new setting is False.

This adds one more step for users before signing in with an external provider.

> You are about to sign in using a third party account from GitHub.
> [ Continue ]

I have changed our list of links to be a form,
so it still is just a click away inside our platform,
but a link from outside will require the user to click on "continue".
We can just set this setting to True if we want too,
but there is a security notice that explains why isn't a good idea https://github.com/pennersr/django-allauth/blob/master/ChangeLog.rst#security-notice.
We need to update the CSS from .com too, and I may need help with the .org CSS..

### 0.48.0

> The newly introduced ACCOUNT_PREVENT_ENUMERATION defaults to True impacting the
> current behavior of the password reset flow.

We want that.

> The newly introduced rate limitting is by default turned on. You will need to
> provide a 429.html template.

We want this, I have added a 429.html template :)

> The default of SOCIALACCOUNT_STORE_TOKENS has been changed to False. Rationale
> is that storing sensitive information should be opt in, not opt out. If you
> were relying on this functionality without having it explicitly turned on,
> please add it to your settings.py.

We rely on this, I have set it to true.

### 0.49.0

> Changed naming of internal_reset_url_key attribute in
> allauth.account.views.PasswordResetFromKeyView to reset_url_key.

We don't override this view.

Closes https://github.com/readthedocs/readthedocs.org/issues/9122

### CODE REVIEW

**Comment by stsewd** [comment]
This is how it looks like with the changes :/

Screenshot from 2022-05-19 17-30-54
Screenshot from 2022-05-19 17-11-55

**Comment by stsewd** [comment]
The new settings are working as expected locally with ngrok :)

**Comment by ericholscher** [comment]
@stsewd is this PR waiting on frontend fixes?

**Comment by agjohnson** [comment]
The import page definitely needs a fix, that doesn't look great. The padding on the buttons isn't a big deal, but should also be an easy fix.

**Comment by stsewd** [comment]
> @stsewd is this PR waiting on frontend fixes?

yeah, just the CSS part is missing, it also needs to be fixed on .com.

We could also leave it as before, but users will need to press another button to connect their account

> You are about to sign in using a third party account from GitHub.
> [ Continue ]

currently this is done in a single click

**Comment by agjohnson** [comment]
My instance isn't booting, so can't test anything at the moment. But the issue is that `form` has default padding/margin that is different from `a` and these need updated for display in a list. This is the easiest fix.

**Comment by agjohnson** [comment]
Also, I assume https://readthedocs.org/accounts/social/connections/ is likely affected too, as it also uses `a` for the buttons.

**Review by agjohnson — COMMENTED** [review]
The changes included here so far look good, but the styles on at least `li > form > button` need fixed to merge this.

**Comment by stsewd** [comment]
OK, I think I was able to fix this, mainly just took the old values and put them on a new rule. Find the differences:

Screenshot from 2022-06-02 19-59-53
Screenshot from 2022-06-02 19-58-59
Screenshot from 2022-06-02 19-58-21

**Review by humitos — APPROVED** [review]
Looks good to me!

Do we need to care about any kind of data migration of similar?

**Review by agjohnson — APPROVED** [review]
CSS changes look good!

**Comment by stsewd** [comment]
> Do we need to care about any kind of data migration of similar?

Nope, nothing has changed on the models

**Comment by stsewd** [comment]
There is a PR on .com that we need to merge too

**Pull request merged**
