### PR TITLE
Run checkout inside docker

### PR DESCRIPTION
**Pull request by stsewd**
The title isn't 100% true,
because it depends on the settings (if docker is enabled).
There are still commands being executed outside docker #5673.

Blocked on #5673 
Related to #5672

### CODE REVIEW

**Comment by humitos** [comment]
Is this strictly blocked on #5673? I think these are separate things and we can start running these commands from inside the container and then migrate the rest once we have made a decision.

Although, before merging this PR we should make a PR compatible with the Corporate site.

**Comment by stsewd** [comment]
Yeah, this isn't really blocked, but it feels weird executing the same set of commands in different environments. It could lead to some surprises using different git daemons? I don't know. Better safe than sorry? p:

**Comment by humitos** [comment]
> It could lead to some surprises using different git daemons?

This is a good point, yes. I'm not sure if we have the same `git` version inside the container than outside.

**Comment by humitos** [comment]
I just realized that executing `git` from inside the container may requires another change as well. On which servers could be `sync_repository_task` executed when triggered? If the answer includes `webXX` we may need to limit it the `builder` queue because web servers do not have docker.

**Comment by stsewd** [comment]
@humitos we can't merge this till we can retrieve the git data from inside the container.

**Comment by humitos** [comment]
This PR was superseded by #6436. Feel free to re-open if it's still valid.

**Pull request closed without merging**
