### PR TITLE
remove search_analytics

### LINKED ISSUE #6217: Remove `SEARCH_ANALYTICS` Feature Flag
Remove `SEARCH_ANALYTICS` Feature Flag

Ref: [#6192 (comment)](https://github.com/readthedocs/readthedocs.org/pull/6192#issuecomment-536587714)

### PR DESCRIPTION
**Pull request by krptic07**
I have removed the search_analytics flag, but i think the function is needed so didn't change the view.

Closes #6217

### CODE REVIEW

**Comment by stsewd** [comment]
The flag still needs to be removed from the docs. You can run the tests locally to check that everything is working https://docs.readthedocs.io/en/stable/development/tests.html in your PR

**Comment by krptic07** [comment]
I ran the test locally, there is a problem in doc_extensions.py, desc variable is referenced before assignment. What should i do?

**Comment by stsewd** [comment]
> I ran the test locally, there is a problem in doc_extensions.py, desc variable is referenced before assignment. What should i do?


There is a reference to the setting in the docs, that should be removed.

**Comment by stsewd** [comment]
This was already done in https://github.com/readthedocs/readthedocs.org/pull/6447

**Pull request closed without merging**
