### PR TITLE
Feature flag: remove unused ones

### PR DESCRIPTION
**Pull request by humitos**
Follows what's described in #9779.

This initial PR only removes feature flags that are not used at all, or are enabled by default to all the projects. Note that each commit removes one and only one feature flag. This could be useful while reviewing.

Once we merge this PR, we **we have to remove all the `Feature` rows from the db** to avoid future confusions as I had to deal with today 😄 

Next iteration will remove more feature flags that require communication to users or some internal discussion.

### CODE REVIEW

**Comment by benjaoming** [comment]
This is super nice!! The shear amount of feature flags is pretty uphill to look at as someone trying to understand _how things work_.

> Once we merge this PR, we we have to remove all the Feature rows from the db to avoid future confusions as I had to deal with today smile

I was asking @stsewd about the same [last week](https://github.com/readthedocs/readthedocs.org/pull/10394#pullrequestreview-1465702241) :)

**Review by benjaoming — APPROVED** [review]
Yes, it was tricky to review :) Some Feature flags were always _on_ and some feature flags were always _off_... so when the flag is removed, we have to check that conditionals are restored with the correct assumption :)

I looked at the checks and they seem like Prospector bugs. I think we should be safe and that Prospector and several test cases would fail if an unreferenced feature flag was left.

Tests need to be updated. But once they work, everything should be fine :+1:

**Comment by benjaoming** [comment]
Have you seen the current test errors (network errors) in other PRs? I don't think that I've seen it recently, so just wondering that i _could_ be something related to these changes.

**Comment by humitos** [comment]
Yeah, it was a missing mock.

**Pull request merged**
