### PR TITLE
Addons: add a notification on each Sphinx build

### PR DESCRIPTION
**Pull request by humitos**
Temporary notification added to all builds using Sphinx to build their docs. This code should be removed after October 7th, when this behavior becomes the default.

I'm not sure if this is the direction we want to go or not, but I think we want to communicate this as much as possible.

Screenshot_2024-08-05_17-52-28

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
This makes sense to me. Over-explaining stuff is :100:

How does this display on the old dashboard?

**Comment by humitos** [comment]
> How does this display on the old dashboard?

It seems the old dashboard does not render the header of the notifications.

Screenshot_2024-08-06_12-14-34

**Comment by humitos** [comment]
I added a new commit to render the notification's header. It looks like this now:

Screenshot_2024-08-06_12-17-32

**Review by agjohnson — APPROVED** [review]
Both of these look great :100:

**Pull request merged**
