### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ericholscher**
---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--10130.org.readthedocs.build/en/10130/

- Developer's documentation (`dev`): https://dev--10130.org.readthedocs.build/en/10130/

### CODE REVIEW

**Review by humitos — APPROVED** [review]
I love the diff!

Screenshot_2023-03-08_22-42-40

**Review by benjaoming — APPROVED** [review]
:+1:

**Comment by ericholscher** [comment]
> I love the diff!
> 
> Screenshot_2023-03-08_22-42-40

@humitos Are you seeing that at https://docs--10130.org.readthedocs.build/en/10130/build-customization.html ? I don't see it 🙃

**Comment by ericholscher** [comment]
Ah... I think because it got merged 😆

**Comment by humitos** [comment]
Yeah, that should be

**Pull request merged**
