### PR TITLE
APIv3: return `permissions` expandable field on projects

### PR DESCRIPTION
**Pull request by humitos**
Add `?expand=permissions` to project list/detail API endpoints.

Related https://github.com/readthedocs/ext-theme/issues/128

### CODE REVIEW

**Comment by humitos** [comment]
@agjohnson I think we want to move away from expandable fields because it's pretty complex. So, we may not want to use this PR at all -- cc @stsewd

**Comment by agjohnson** [comment]
What is the complexity here? This PR is very useful in removing the page load time on project/organization/build listings.

If we aren't using expand fields, what other options do we have here for returning this data in a single API request? Does this need to be a second API request from the dashboard?

**Comment by stsewd** [comment]
This field is specific to the current user, so it shouldn't be a problem. But be aware that this will probably add lots of querysets when listing projects...

**Comment by agjohnson** [comment]
Good point, I am only using this in the detail view. If there is a way to only allow this expansion on detail views, I think that should be enough as well. Or we can monitor this and see if it is ever used/abused. This should never be documented for users, though it is in a public request that users can inspect too.

**Comment by agjohnson** [comment]
Do we need to do anything additional with this PR? This feels like a fairly small change, as are the changes to use this in 

- https://github.com/readthedocs/ext-theme/pull/404

**Comment by humitos** [comment]
I'm not 100% sure about where we are regarding the expandable fields and [this comment](https://github.com/readthedocs/readthedocs.org/pull/10978#issuecomment-2223622150) from @stsewd. I'm happy to add some test cases to this PR and mark it as ready for review after that if that's the required work here.

**Comment by agjohnson** [comment]
@humitos I'd like to get this merged so we can get the new dashboard PR merged in too.

It sounds like this change here is not a big concern, as it's on a detail view. So seems like we just want some tests here for now?

@stsewd are you concerned about this PR at all?

**Comment by stsewd** [comment]
> @stsewd are you concerned about this PR at all?

Nope.

> It sounds like this change here is not a big concern, as it's on a detail view. So seems like we just want some tests here for now?

+1 on tests

**Review by stsewd — APPROVED** [review]
This will likely break tests on .com, make sure to update them after this PR is merged.

**Pull request merged**
