### PR TITLE
Docs: Add opengraph

### PR DESCRIPTION
**Pull request by ericholscher**
* before: https://www.opengraph.xyz/url/https%3A%2F%2Fdocs.readthedocs.io%2Fen%2Fstable%2F
* after: https://www.opengraph.xyz/url/https%3A%2F%2Fdocs--10066.org.readthedocs.build%2Fen%2F10066%2F

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--10066.org.readthedocs.build/en/10066/

- Developer's documentation (`dev`): https://dev--10066.org.readthedocs.build/en/10066/

### CODE REVIEW

**Comment by benjaoming** [comment]
@ericholscher does this need some kind of graphic be made for SOME cards?

**Comment by ericholscher** [comment]
Hrm yea, it doesn't like svg's it seems..

**Comment by ericholscher** [comment]
The image will work after merge, because reasons 🙃

**Comment by ericholscher** [comment]
It now also shows the first image as the preview, which is pretty neat! Better than the logo I think.

**Comment by benjaoming** [comment]
Yes, having the logo is nice in some cases, but often it makes previews large and a big clumsy. Much better to have an individual image when possible :+1:

**Review by benjaoming — APPROVED** [review]
LGTM :+1: Funky stuff with the canonical URL on PR builds, but that's another reason why I want Sphinx to have an explicit `canonical_url` context variable.

**Comment by benjaoming** [comment]
Really liking that we can have some actual SOME previews on documentation :100:

**Comment by ericholscher** [comment]
Yea, I think it'll be nice 👍

**Pull request merged**
