### PR TITLE
Call distinct to the end of the querysets

### PR DESCRIPTION
**Pull request by stsewd**
This allow us to extend easily the querysets
and use `|` (or) to merge to querysets
(this can't be done after calling distinct)

This needs changes in .com

### CODE REVIEW

**Comment by stsewd** [comment]
I did some builds and navigate the site, everything keeps working

**Comment by ericholscher** [comment]
Seems like this could likely use some additional tests. I'm guessing the `distinct()` call is because we're adding users querysets which could already exist in the base queryset? I imagine you have a bit more context for why this is needed, and should be written down somewhere, and likely shown in a test.

**Comment by stsewd** [comment]
So, `_add_user_repos` is the one query that can generate duplicate results (as far as I can tell). When `.distinct` is used, we can't no longer do `old_queryset | new_queryset`, this doesn't allow us to merge to results (likely this help us to fix .public ignoring previous filters or maybe not).

Another reason for this is to be consistent too, we sometimes are returning `.distinct` which can't use `\` and other times just a _normal_ queryset. And this would help me to move the auth checking to a central place. See https://github.com/readthedocs/readthedocs-corporate/pull/559/commits/0e39f8bffeebe2399454db514fe69d8c9cfbb446

**Comment by stsewd** [comment]
Coverage is good https://codecov.io/gh/readthedocs/readthedocs.org/pull/5872/diff, but it can be improved

**Comment by ericholscher** [comment]
I don't care about coverage as much as making sure we actually have a test for the logic we care about. We should make sure we have a test that is creating duplicated objects, and then confirming they are removed.

**Comment by stsewd** [comment]
@humitos feel free to add the comment. We have git log and tests to prevent future us from breaking this.

**Comment by humitos** [comment]
> We have git log and tests

git log and tests are not docs :wink:

**Pull request merged**
