### PR TITLE
Remove feeds.py

### LINKED ISSUE #6222: Remove rss feed
All code related to this should be removed, isn't useful.

https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/core/urls/__init__.py#L55-L66

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #6222

### CODE REVIEW

**Comment by stsewd** [comment]
Thanks for the PR, please merge master into this branch to get the CI running again.

**Comment by Patil2099** [comment]
How to that ? @stsewd 
Thanks

**Comment by stsewd** [comment]
```bash
git checkout master
git pull origin master
git checkout your-branch
git merge master
git push
```

Also, I noticed you are making your changes on master, you should do new changes on another branch, you can check some resources to learn git on https://try.github.io/

**Comment by stsewd** [comment]
This was already fixed in https://github.com/readthedocs/readthedocs.org/pull/6348

**Pull request closed without merging**
