### PR TITLE
Analytics: add Plausible to our dashboard

### LINKED ISSUE #9604: Application: use Plausible for dashboard analytics
We started using Plausible on our new website, we should eventually consolidate our own application/dashboard analytics there as well. This might aid in correlating website traffic to subscription creation/etc.

I don't believe we're tracking anything of moderate importance currently, so this should be fairly low friction.

### PR DESCRIPTION
**Pull request by humitos**
Use Plausible for dashboard's analytics.

Closes #9604

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
:+1: We'll also need this on the new dashboard templates

**Comment by humitos** [comment]
I'm not merging this one before, because @ericholscher said that maybe this generates a lot of traffic and we may want to with commercial-only first. However, the PR is here and we can decide _when_ we want to merge it.

**Comment by ericholscher** [comment]
Yea, I think .org gets a lot of traffic, and I'm not sure how useful it would be. I'd be 👍 on starting with admin pages or only for logged in users, if there's specific questions we want to ask vs. just capturing how many project detail pages get hit each day.

**Comment by humitos** [comment]
I like the idea of logged-in users. I will adapt this PR to follow that.

**Review by ericholscher — APPROVED** [review]
Good start 👍

**Pull request merged**
