### PR TITLE
Remove skip submodules flag

### PR DESCRIPTION
**Pull request by stsewd**
Now we have a way of skip submodules
(using a configuration file).
We should notify users that have a feature flag to migrate.

### CODE REVIEW

**Comment by humitos** [comment]
>  We should notify users that have a feature flag to migrate.

We should do this before merging this PR and give them some time to make the migration. After that, we can merge and deploy, I'd say. Otherwise, we will break their builds automatically once this gets deployed.

**Comment by stsewd** [comment]
Blocking this till all users using the flag have migrated to a config file.

**Comment by humitos** [comment]
> Blocking this till all users using the flag have migrated to a config file.

I'm not sure we will ever know this. I suppose we can close this PR that will be open forever otherwise and revisit it once we have deprecated Config V1.

**Comment by stsewd** [comment]
> I'm not sure we will ever know this.

We know what projects are using the `skip_submodules` flag, we have to notify them

**Comment by humitos** [comment]
Oh! Forget what I said. I misread the comments. You are right.

**Comment by stsewd** [comment]
We have 6 projects in .org: amara, chassis, firesim, qwat, rematch, u-bmc

Not sure how to proceed, and how many we have in .com :)

**Comment by ericholscher** [comment]
@stsewd we need to contact them all and help them move to the YAML file. We could even go as far as submitting a PR for their repo with a proper config, if we wanted (especially if we had a PR builder :D)

**Comment by humitos** [comment]
We only have 6 projects using this feature flag, so contacting them or making a PR on their repo is affordable if we want to go faster. @stsewd feel free to do the one you like most ;)

**Comment by stsewd** [comment]
@humitos I'm more worried about user using this in the corporate site, we need to inform those users too.

**Comment by humitos** [comment]
I'm about to contact these users to let them know how to upgrade their projects to keep building properly.

**Comment by humitos** [comment]
/remind me to polish this PR and try to merge on August 15th 2019 after all the users have implemented the Config File V2 with the `exclude` option.

**Comment by humitos** [comment]
Unblocking this issue.

All the users were notified and most of them replied in time communicating that they already did the required change in their YAML files.

We are ready to merge this PR once the conflicts are resolved and deploy.

**Comment by stsewd** [comment]
@humitos done

**Pull request merged**
