### PR TITLE
Import Repository Account Filter Display Provider Name

### PR DESCRIPTION
**Pull request by saadmk11**
closes https://github.com/readthedocs/readthedocs.org/issues/9718

### Output:
Screenshot from 2022-12-29 16-11-52

**Note:** The Remote Organisation API (`/api/v2/remote/org/`) does not return the Provider Name with correct case but the Account API Does. We can either change the Remote Organisation API to return the display name or update `readthedocs/projects/static-src/projects/js/import.js` to change the name depending on the value (e.g.: `github` -> `GitHub`)

### CODE REVIEW

**Comment by benjaoming** [comment]
Hi @saadmk11 :wave: 

I think the solution looks like a good a simple way to address this.

When generating `display_name` is there any context available to see how many providers are displayed? Or can that context be added and applied easily?

This could be great to avoid that users with just 1 provider (I'm guessing most users) do not see "GitHub" or "Bitbucket" displayed for no apparent reason.

**Comment by saadmk11** [comment]
> When generating `display_name` is there any context available to see how many providers are displayed? Or can that context be added and applied easily?

I don't think so. It is stored in `ProjectImportView.organizations_raw` / `ProjectImportView.accounts_raw`. I would always show the providers, a not so common case can be that the user forgot which provider they connected and they need to check their account settings to figure it out because the Profile picture and username are same.

**Comment by benjaoming** [comment]
It's also not too bad to always display the provider name :+1:

What about writing some generic short notation like `github/acme` instead of `acme (github Organization)` ? I'm not even sure if both Bitbucket and GitLab call these "organizations". I think on Bitbucket, it's called a Workspace :upside_down_face:

**Comment by saadmk11** [comment]
> It's also not too bad to always display the provider name +1
> 
> What about writing some generic short notation like `github/acme` instead of `acme (github Organization)` ? I'm not even sure if both Bitbucket and GitLab call these "organizations". I think on Bitbucket, it's called a Workspace upside_down_face

Screenshot from 2023-01-08 18-20-30

**Review by benjaoming — APPROVED** [review]
LGTM :100: 

This way of writing it makes it easy for me to quickly skim the list when there are multiple providers.

In other cases, it still makes the list look good by clearly indicating what belongs to a private profile and what belongs to an organization.

A secondary effect: Maybe not all users will know that Read the Docs supports connecting multiple accounts. The design of the list hints that this is an option. By making the list appear this way, we could in the future add a link below "connect additional Git providers" or similar.

**Comment by humitos** [comment]
This page has changed considerably in our new templates and I'm not sure it makes sense to merge this work anymore. If anything, we should make the changes in the new templates.

This is an example of how it's going to be:

Peek 2023-03-07 11-02

Please, feel free to comment here if the new idea does not cover the case this PR was covering

**Comment by saadmk11** [comment]
> This page has changed considerably in our new templates and I'm not sure it makes sense to merge this work anymore. If anything, we should make the changes in the new templates.
> 
> This is an example of how it's going to be:
> 
> Peek 2023-03-07 11-02 [ Peek 2023-03-07 11-02 ](https://user-images.githubusercontent.com/244656/223389683-1d25c2f4-4b26-4a9a-971a-85577d61f7c3.gif) [ ](https://user-images.githubusercontent.com/244656/223389683-1d25c2f4-4b26-4a9a-971a-85577d61f7c3.gif)
> 
> Please, feel free to comment here if the new idea does not cover the case this PR was covering

@humitos This looks nice. :100:  Is the new UI available for testing?

**Comment by humitos** [comment]
@saadmk11 not yet, unfortunately. We are working hard to make a public beta release soon, tho 👍🏼

**Comment by humitos** [comment]
Hey @saadmk11! I'm happy to let you know how to jump into the private alpha/beta instance that contains the new templates. Take into account that this instance is not publicly accessible for everybody and, in theory, nobody knows about it. We are using it internally to test the progress on this work.

The URL to connect to it is https://beta.readthedocs.org. You need to manually create a cookie in your side with the key `beta` and the value `true` (I've done this with Firefox by pressing `F12 -> Storage -> Cookies -> "Plus" sign`) . That's all 😅 

Feel free to open an issue in this repository with your feedback in case you have any. I'm happy to receive more general feedback and also specific feedback. However, keep in mind that things can drastically change and nothing is written in stone 😄

**Comment by saadmk11** [comment]
> Hey @saadmk11! I'm happy to let you know how to jump into the private alpha/beta instance that contains the new templates. Take into account that this instance is not publicly accessible for everybody and, in theory, nobody knows about it. We are using it internally to test the progress on this work.
> 
> The URL to connect to it is https://beta.readthedocs.org. You need to manually create a cookie in your side with the key `beta` and the value `true` (I've done this with Firefox by pressing `F12 -> Storage -> Cookies -> "Plus" sign`) . That's all sweat_smile
> 
> Feel free to open an issue in this repository with your feedback in case you have any. I'm happy to receive more general feedback and also specific feedback. However, keep in mind that things can drastically change and nothing is written in stone smile

Thanks will try it out :)

**Pull request closed without merging**
