### PR TITLE
Support the new Google analytics gtag.js

### PR DESCRIPTION
**Pull request by davidfischer**
- This applies to docs and to the dashboard
- This is backwards compatible with the old UA-XXX properties assuming nothing custom is going on
- Supports the new G-XXXX properties
- Continues to support disabling analytics and do not track
- Sends custom dimensions like before
- Shorter cookie expiry like before

Fixes https://github.com/readthedocs/readthedocs.org/issues/7662

## Testing

The easiest way to test this is to set `settings.GLOBAL_ANALYTICS_CODE` and rebuild some documentation and/or view the dashboard and verify that GA is loaded and data is sent (the `collect` call in the screenshot). There should be another call when clicking the flyout menu.

Note that I didn't build the static files as part of this PR so you'll need to run `npm run build` to do that. I will do that *right before* merging this to avoid conflicts.

Screen Shot 2020-11-23 at 11 55 17 AM

### CODE REVIEW

**Comment by ericholscher** [comment]
Not an issue here, but I did see `"global_analytics_code": "None"` in my testing prior to setting the variable. Not gonna be an issue for us in prod, but probably worth fixing at some point.

**Review by ericholscher — APPROVED** [review]
This looks 💯  in my testing. I tested the dashboard and the in-doc pageviews and events. I think we're good to ship it.

**Review by stsewd — APPROVED** [review]
I was able to see this as well. Had to use chromium bc my firefox was blocking everything :D. I have rebuilt the static assets

**Comment by JuanDCG** [comment]
With `"global_analytics_code": "G-XXXXXX"` it is now working for me.

Thank you!

**Comment by sachin-suresh-rapyuta** [comment]
> With `"global_analytics_code": "G-XXXXXX"` it is now working for me.
> 
> Thank you!

@JuanDCG - I am at the step where I just added my ReadtheDocs website URL to Google Analytics Web stream, where I have my G-ID now. I pasted this ID in ReadtheDocs admin's `Analytics code` field. 

1. Can you please let me know the next steps?
2. Is installing Google tag mandatory?

**Comment by JuanDCG** [comment]
> > With `"global_analytics_code": "G-XXXXXX"` it is now working for me.
> > Thank you!
> 
> @JuanDCG - I am at the step where I just added my ReadtheDocs website URL to Google Analytics Web stream, where I have my G-ID now. I pasted this ID in ReadtheDocs admin's `Analytics code` field.
> 
>     1. Can you please let me know the next steps?
> 
>     2. Is installing Google tag mandatory?

Sorry, It was 2 years ago and nowadays I can't help you.

**Pull request merged**
