### PR TITLE
Changed Dicts to NamedTuple

### PR DESCRIPTION
**Pull request by vitorsv1**
Fix Issue #7798

### CODE REVIEW

**Comment by vitorsv1** [comment]
Thanks for the quickly reply, I'm working on it right now

**Comment by humitos** [comment]
@stsewd can you give it a final review so we can merge it?

@vitorsv1 would you like to solve the conflicts?

**Comment by stsewd** [comment]
yeah, +1 on using a data class, but we should check if they work correctly with celery.

**Comment by humitos** [comment]
Cool! I will close this PR for now since we haven't been able to prioritize this work. I also commented on the issue about the decision of using dataclasses.

**Pull request closed without merging**
