### PR TITLE
Migrate jsonfield.JSONField to postgres.fields.JSONField

### PR DESCRIPTION
**Pull request by humitos**
Using the JSONField from django postgres itself allows us to perform queries in a more detailed way, being able to query over the JSON keys/values itself:

```python
In [5]: Build.objects.filter(_config__build__image='readthedocs/build:testing').count()                                                                                                     
Out[5]: 13

In [8]: Build.objects.filter(_config__python__version=3).count()                                                                                                                            
Out[8]: 22

In [16]: Build.objects.filter(_config__formats__contains=['htmlzip']).count()                                                                                                               
Out[16]: 23
```

The data migration was transparent. I just ran the migration automatically created by Django. I guess this will take some time in production database since we have a lot of `Build.config` and `HttpExchange.*` fields to migrate.

### CODE REVIEW

**Comment by humitos** [comment]
I didn't remove the `jsonfield` requirement because it's used in the old migrations (when the field was added) --although, we may want to remove it and just change those fields to the Django one, but I'm not sure what will happen when the new migration with the change of the field is executed again.

**Comment by humitos** [comment]
This needs some coordination to deploy because "we can't just run the migration as is" since it will produce instances using the old code (`jsonfield.JSONField`) trying to read the new PostgresSQL's JSONField and it will break.

This guide could be helpful to make a decision about how to deploy this: https://tech.polyconseil.fr/migrating-from-json-to-jsonb.html

**Comment by stsewd** [comment]
This also means we not longer support other databases, only postgress. And for testing we need to use postgress.

**Comment by stsewd** [comment]
> I didn't remove the jsonfield requirement because it's used in the old migrations (when the field was added)

I think we can squash migrations to get around that

**Comment by davidfischer** [comment]
> This also means we no longer support other databases, only postgress. And for testing we need to use postgress.

This is true. Wouldn't it cause issues for unit testing where we use sqlite?

**Comment by ericholscher** [comment]
I'd like to only support postgres in general. Testing on sqlite is not great, and will likely hide other issues, so probably worth making the switch officially.

**Comment by humitos** [comment]
Postgres field won't be needed anymore once we migrate to Django 3.x that has native support for JSON field in all the db backend supported. I don't think we should put effort here before migrating to 3.x

**Pull request closed without merging**
