### PR TITLE
Revert "Build: pass `PATH` environment variable to Docker container (#10133)"

### PR DESCRIPTION
**Pull request by ericholscher**
This reverts https://github.com/readthedocs/readthedocs.org/pull/10172 & https://github.com/readthedocs/readthedocs.org/pull/10133

### CODE REVIEW

**Review by stsewd — APPROVED** [review]
Looks like we need to run pre-commit

**Comment by stsewd** [comment]
We may want to run pre-commit in another commit, and do a merge commit instead of squash+rebase, to avoid any conflicts when merging main into our release branches.

**Comment by ericholscher** [comment]
pre-commit won't fix this, because it's silly linting errors on changed files 👎

**Comment by ericholscher** [comment]
I'm not really sure how to make this pass, it passes locally:

```
-> pre-commit run --files readthedocs/doc_builder/environments.py
check for added large files..............................................Passed
check python ast.........................................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check that scripts with shebangs are executable..........................Passed
check toml...........................................(no files to check)Skipped
check vcs permalinks.....................................................Passed
debug statements (python)................................................Passed
fix utf-8 byte order marker..............................................Passed
fix end of files.........................................................Passed
fix python encoding pragma...............................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
trim trailing whitespace.................................................Passed
mixed line ending........................................................Passed
autoflake................................................................Passed
prospector...............................................................Passed
darker...................................................................Passed
blacken-docs.............................................................Passed
```

**Comment by stsewd** [comment]
@ericholscher that's because the commit is already done, you can run `pre-commit run --from-ref main --to-ref HEAD`

**Comment by ericholscher** [comment]
This was merged into `main` manually 👍

**Pull request closed without merging**
