### PR TITLE
Customize default build media storage for the FS

### PR DESCRIPTION
**Pull request by davidfischer**
Edit: closely mirror the logic to get the production media path:

https://github.com/readthedocs/readthedocs.org/blob/557c875fa4d74e1cb69146e005375595f80adf91/readthedocs/projects/models.py#L584-L598

### CODE REVIEW

**Comment by davidfischer** [comment]
> do we actually want to pass a location when on the .org

In production, this class is not used on .org at all. We use an Azure storage class that mixes in `BuildMediaStorageMixin`. In development for .org, perhaps a better approach is to actually have `settings.PRODUCTION_MEDIA_ARTIFACTS` have meaning. That is, we could actually write build artifacts there as opposed to it being a meaningless, non-existent folder which it is now. In that case, we could just always make this class use `settings.PRODUCTION_MEDIA_ARTIFACTS`.

**Comment by davidfischer** [comment]
The biggest drawback to what I outlined above as far as I can tell is that people will have to move their built artifacts to a different directory in dev.

**Comment by agjohnson** [comment]
That might make sense. We can always work around having a secondary path, it's going to be much harder to tease apart the build output path, normal media path usage, and improper/old static file media path usage. Locally, we'd probably still run the local build storage on community development, we don't want to be writing to Azure from local dev.

We can come back to this case, but I'd agree that the production artifact path should be used in local development as well.

**Comment by agjohnson** [comment]
I'll be applying this as hotfix to .com later, the change seems to look good

**Comment by davidfischer** [comment]
> Locally, we'd probably still run the local build storage on community development, we don't want to be writing to Azure from local dev.

Just to be clear, I completely agree. I'm proposing basically having `prod_artifacts/media` exist in development.

**Comment by ericholscher** [comment]
> I'm proposing basically having prod_artifacts/media exist in development.

I think this is probably the right approach. It also works well w/ the move to having all the build media served via the webs as well, instead of directly off the media server.

**Pull request merged**
