### PR TITLE
Dependencies: use GitHub Action + pip-tools

### LINKED ISSUE #9273: pyup or dependabot together with pip-tools
pyup does not understand pip-tools (pip-compile), so I was taking a look at dependabot and it seems it does: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems

We should probably migrate to it and use pip-tools for all our dependencies.

### PR DESCRIPTION
**Pull request by humitos**
I finally decided to use a custom GitHub Action + pip-tools because:

- pyup does not support pip-tools
- pur does not pin transitive dependencies
- dependabot says it supports pip-compile but doesn't work

So, we are now running `pip-compile` weekly and creating a Pull Request with the
changes performed to the output files. From there, we can decide if we merge it
or not.

Note the GitHub action handles the creation of the PR (or the skip of it)
automatically and should not flood us with multiple PRs.

Also note that I'm doing this for `requirements/docs.in` in this PR only to show
how it works and avoid the noise, but I will prepare another PR that uses the
same pattern for all the other requirements files.

Closes #9273

----
:books: Documentation preview :books:: https://docs--9479.org.readthedocs.build/en/9479/

### CODE REVIEW

**Comment by humitos** [comment]
Here is an example of this GitHub Action run in `sphinx-hoverxref` repository: https://github.com/readthedocs/sphinx-hoverxref/pull/221. Looks great!

**Comment by humitos** [comment]
@stsewd can you review this PR please? I'd like to avoid accumulating conflicts on it and start testing the new packages locally.

**Comment by stsewd** [comment]
```
ERROR: Cannot install requests==2.27.1 and requests==2.28.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.27.1
    The user requested requests==2.28.1
```

CI is failing

**Comment by humitos** [comment]
@stsewd apart from that, the rest of the PR looks 👍🏼 ?

**Comment by stsewd** [comment]
> @stsewd apart from that, the rest of the PR looks 👍🏼 ?

Yeah

**Pull request merged**
