### PR TITLE
don't export `GIT_DIR`

### LINKED ISSUE #8288: Custom LFS integration has broken unexpectedly
## Details

The SecureDrop project uses https://github.com/freedomofpress/securedrop-docs as its documentation repo. It uses LFS because screenshots are updated with each release, which would otherwise balloon the repo size.

We are aware that LFS is not officially supported (#1846), but have so far relied on a commonly used method for installing `git-lfs` via `conf.py` (https://github.com/freedomofpress/securedrop-docs/blob/main/docs/conf.py#L21-L27). This method has stopped working unexpectedly approximately 2-3 days ago, causing all images in our documentation to break (they are served as LFS pointers).

We would appreciate any light you can shed on changes to the RTD build environment that may have caused this breakage. We have attempted to resolve it using various strategies, e.g., by installing `git-lfs` as a package, to no avail so far. It appears to us that even when the LFS checkout is working as expected, at some point during the build process, the actual images are not copied correctly.

Further notes on our technical investigation so far can be found at https://github.com/freedomofpress/securedrop-docs/issues/234 . We can of course revert to a non-LFS repo, but if there is a straightforward fix or lead for us to pursue, we would appreciate any pointers.

### PR DESCRIPTION
**Pull request by RuRo**
See #8288 for more info. Fixes #8288.

### CODE REVIEW

**Comment by humitos** [comment]
Hi @RuRo and thanks for your PR. I haven't tested the code locally yet (*), but it seems there are 16 tests failing after this change. Can you take a look into that first?

(*) a good test would be to build `test-builds` with the `git-lfs` branch without modifications and it should pass and show the image in the page.

**Comment by RuRo** [comment]
So I ended up just removing the `GIT_DIR` altogether instead of adding `GIT_WORK_TREE`. It seems, that the `GIT_DIR` export wasn't actually used anywhere since the `cwd` is always inside the relevant repo (at least it seems to be the case in all the tests).

I've also built the `git-lfs` branch from the [`test-builds` repo](`https://github.com/readthedocs/test-builds.git`) and the image is displayed correctly. Although the is some error in the `latexmk` step (I don't use latex myself, so I am not 100% sure, what is the issue there).

**Review by stsewd — APPROVED** [review]
So, we always set the cwd to `self.working_dir`

https://github.com/readthedocs/readthedocs.org/blob/babbdf058f1ae4eade27b4ef579e6b142a5dffba/readthedocs/vcs_support/base.py#L101-L104

So it makes sense to just remove that env var :+1:

**Comment by ericholscher** [comment]
I do worry that this might break things -- but let's try it and see if something else blows up :/ We might end up reverting pretty quickly, but it does seem like it isn't needed. I imagine some users could be depending on this somehow though :/

**Comment by RuRo** [comment]
> I imagine some users could be depending on this somehow though :/

I think, that prior to #8263, these environment variables weren't even visible in the step that ran the users `conf.py`. In fact, that's why `git-lfs` broke in the first place. So, in theory, any breakage should be entirely in the `readthedocs` codebase, and it is hopefully covered by all the tests. Hopefully. 😅

**Comment by ericholscher** [comment]
I'm guessing this is actually breaking from `expand_vars=False` being passed, and not the GIT_DIR? I'm wondering if git-lfs is depending on some kind of env variable in the backend of git to do this work.

**Pull request closed without merging**
