### PR TITLE
Eslint fix issues

### PR DESCRIPTION
**Pull request by humitos**
I fixed the indentation of the return keyword, but I think the problem is/was that pre-commit adds a newline to the bundled file. I skipped pre-commit this time when doing the commit.

I understand this should fix the issue with eslint.

### CODE REVIEW

**Comment by humitos** [comment]
Locally, I'm getting this error:

```
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
```

I have no idea what it means 🙃

**Comment by agjohnson** [comment]
Ahh yes, this is an error that ultimately means the Node.js version is unexpected. `primordials` I think is a Node 8 construct, removed in later versions (or maybe I have that backwards, and likely have the version wrong).

This isn't the first time we've noticed the error either, but I'm guessing it's probably because a newer Node was used to compile/test?

**Comment by agjohnson** [comment]
Oh, and actually, I think I know what is happening. All of the lines that are warning will not normally fail the build, the lines that are `error` will though. I'm guessing the hack that got added those 3 errors

**Comment by humitos** [comment]
Let see if fixing those 3 makes this to work.

**Comment by humitos** [comment]
> Ahh yes, this is an error that ultimately means the Node.js version is unexpected. `primordials` I think is a Node 8 construct, removed in later versions (or maybe I have that backwards, and likely have the version wrong).

Hrm, "in theory" we are using a Docker container to build the assets, so the version of Node should have been pinned since we started doing that. Maybe we pinned to a wrong version? 

https://github.com/readthedocs/readthedocs.org/blob/a72f1753fd12a9777faab5d5a71306ef8af38e37/dockerfiles/docker-compose-assets.yml#L5

**Comment by humitos** [comment]
It worked!

**Comment by agjohnson** [comment]
> Maybe we pinned to a wrong version?

I bet that is it, CI installs Node.js 10

**Pull request merged**
