### PR TITLE
Don't install pygments

### PR DESCRIPTION
**Pull request by stsewd**
Sphinx declares that dependency in the latest version https://github.com/sphinx-doc/sphinx/blob/bec30596a8f7487cad23df532bf02d1b29024dbc/setup.py#L25

and since 1.0 https://github.com/sphinx-doc/sphinx/blob/690fc257e9a539a4c193ba8efe5587f7c102785c/setup.py#L47

ref https://github.com/readthedocs/readthedocs.org/issues/7480
fixes https://github.com/readthedocs/readthedocs.org/issues/7492

### CODE REVIEW

**Review by humitos — COMMENTED** [review]
LGTM! However, this will affect _all the builds_ so I think we should make this a feature flag so we can rollout this smoothly without breaking everything and being safe.

**Comment by stsewd** [comment]
It's installed as a dependency of sphinx, not sure if we need a feature flag for this. Also, builds are broken bc of this.

**Comment by humitos** [comment]
@stsewd Do you know why pygments was originally pinned? You said that since Sphinx 1.0 it's a dependency declared. However, we pinned it while using 1.2.2 at https://github.com/readthedocs/readthedocs.org/commit/5c7c11f68fc717128542d0dacc975ab9303a65b3 for some reason.

**Comment by stsewd** [comment]
@ericholscher should have more context for that change

**Comment by ericholscher** [comment]
Not sure -- that was a long time ago. I think it should be fine to unpin.

**Review by ericholscher — APPROVED** [review]
Seems safe enough 👍

**Pull request merged**
