### PR TITLE
Document setting up connected accounts in dev

### PR DESCRIPTION
**Pull request by davidfischer**
These steps require #6679 to work correctly.

### CODE REVIEW

**Comment by stsewd** [comment]
BTW, with the latest version of allauth (not installed in our req yet, but we will after the django update)

> You can now store OAuth credentials directly in your settings.SOCIALACCOUNT_PROVIDERS settings instead of storing them in the database using a SocialApp record.

**Comment by ericholscher** [comment]
I'd prefer to just have this in a fixture that we can load locally. I don't think docs are the answer here, but just having them automatically setup in dev.

**Comment by davidfischer** [comment]
> I'd prefer to just have this in a fixture that we can load locally. I don't think docs are the answer here, but just having them automatically setup in dev.

The fixture might have to be private. I'm not sure I 100% understand the implications of sharing the secret with the world. I'll have to think about it.

**Comment by humitos** [comment]
@davidfischer I think we should merge this. It's already approved and I think it's useful as it is. We could create a fixture later if we decide that's better/secure. In the meanwhile, we can have this docs up.

**Pull request merged**
