### PR TITLE
Fix import wizard

### PR DESCRIPTION
**Pull request by stsewd**
I think this fixes it (at least makes .com tests green), but we don't have tests for this, so not sure if it doesn't break anything else. @humitos you may want to test it locally.

ref https://read-the-docs.sentry.io/issues/6127455073/?project=161479&query=is%3Aunresolved&referrer=issue-stream&sort=trends&statsPeriod=90d&stream_index=3

### CODE REVIEW

**Review by humitos — CHANGES_REQUESTED** [review]
It works fine on community, but on commercial it fails with

```
RecursionError at /dashboard/import/manual/
maximum recursion depth exceeded
```

It seems that `wizard.get_step_index()` calls `self.steps.current`, which calls again `show_config_step` 😢

**Comment by stsewd** [comment]
> It works fine on community, but on commercial it fails with
> 
> ```
> RecursionError at /dashboard/import/manual/
> maximum recursion depth exceeded
> ```
> 
> It seems that `wizard.get_step_index()` calls `self.steps.current`, which calls again `show_config_step` 😢

I wasn't able to replicate that in tests, did you rebuild your docker image with to use the latest version of the dependency?

**Comment by humitos** [comment]
> I wasn't able to replicate that in tests

Are you able to reproduce this by importing a project?

> did you rebuild your docker image with to use the latest version of the dependency?

Yes.

**Review by humitos — APPROVED** [review]
Let's try this solution and see how it goes.

**Pull request merged**
