### PR TITLE
Update celery requirements to its latest version

### LINKED ISSUE #4643: Upgrade celery to >= 4.2
We may need to do some changes before upgrading celery to 4.2, as we face some issues (https://github.com/rtfd/readthedocs.org/issues/4640).

Some options are:

- Require to run celery (`always_eager=False`) in dev
- Maybe this is a bug on celery?
   - Or maybe we can send a patch to allow to pass the `disable_sync_subtask` option as mention in https://github.com/rtfd/readthedocs.org/issues/4640#issuecomment-422232637

### PR DESCRIPTION
**Pull request by humitos**
Upgrading celery requires to upgrade their dependencies as
well (kombu, redis). By using their latest version, it could help with
the random disconnection of the workers that we suffer sometimes.

After upgrading them all, the errors we have found when we pinned the
versions they all disappeared.

Closes #4643

### CODE REVIEW

**Comment by stsewd** [comment]
Did you test with `ALWAYS_EAGER = True`? Core team should be using it to `False`, but new contributors will hit an error.

Also, this will closes https://github.com/readthedocs/readthedocs.org/issues/4643

**Comment by humitos** [comment]
> Did you test with `ALWAYS_EAGER = True`?

Yes. All tests are ran with `ALWAYS_EAGER = True`.

**Comment by stsewd** [comment]
> Yes. All tests are ran with ALWAYS_EAGER = True.

The error happens when triggering a build, I don't think it was detected inside the tests.

**Comment by humitos** [comment]
Confirm. Triggering a build does work.

**Comment by stsewd** [comment]
So, the issue on celery is still open https://github.com/celery/celery/issues/5330


But I think we don't use this anymore

https://github.com/readthedocs/readthedocs.org/blob/54397a07a1baed5b183c0535093643467c3edaba/readthedocs/core/utils/__init__.py#L27

That's why we don't hit this issue anymore.

**Comment by ericholscher** [comment]
Let's merge this _after_ our deploy today, so we have time to test it out in dev across different environments before we ship it to prod over the holidays.

**Pull request merged**
