### PR TITLE
ngrok: update Install documentation

### LINKED ISSUE #7982: Docs: explain how to use ngrok with Docker setup
While working with external services, like GitHub or Stripe, it's handy to use ngrok (https://ngrok.com) to access the instance running locally on Docker for a domain publicly accessible. However, there are some changes required to make it work.

```diff
diff --git a/docker-compose.override.yml b/docker-compose.override.yml
index e88276dbd..a1d28c6c0 100644
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -52,6 +52,7 @@ services:
       - HOSTIP=${HOSTIP:-}
     extra_hosts:
       - "community.dev.readthedocs.io:10.10.0.100"
+      - "readthedocs.ngrok.io:10.5.0.100"
 
   celery:
     image: community_server:latest
diff --git a/dockerfiles/nginx/proxito.conf b/dockerfiles/nginx/proxito.conf
index 0cd250fab..c2935e42b 100644
--- a/dockerfiles/nginx/proxito.conf
+++ b/dockerfiles/nginx/proxito.conf
@@ -1,7 +1,7 @@
 # Proxito
 server {
     listen 80 default_server;
-    server_name *.community.dev.readthedocs.io *.org.dev.readthedocs.build;
+    server_name *.readthedocs.ngrok.io;
 
     # TODO: serve the favicon.ico from the project/version itself instead
     location /favicon.ico {
diff --git a/dockerfiles/nginx/web.conf b/dockerfiles/nginx/web.conf
index 3d6c6523c..57a2dcc91 100644
--- a/dockerfiles/nginx/web.conf
+++ b/dockerfiles/nginx/web.conf
@@ -2,7 +2,7 @@ server {
     listen 80;
 
     # This should match settings.PRODUCTION_DOMAIN
-    server_name community.dev.readthedocs.io;
+    server_name readthedocs.ngrok.io;
 
     location /favicon.ico {
         proxy_pass http://storage:9000/static/images/favicon.ico;
diff --git a/readthedocs/settings/docker_compose.py b/readthedocs/settings/docker_compose.py
index 15287c29e..cd5ba9bfd 100644
--- a/readthedocs/settings/docker_compose.py
+++ b/readthedocs/settings/docker_compose.py
@@ -15,8 +15,8 @@ class DockerBaseSettings(CommunityDevSettings):
     DOCKER_LIMITS = {'memory': '1g', 'time': 900}
     USE_SUBDOMAIN = True
 
-    PRODUCTION_DOMAIN = 'community.dev.readthedocs.io'
-    PUBLIC_DOMAIN = 'community.dev.readthedocs.io'
+    PRODUCTION_DOMAIN = 'readthedocs.ngrok.io'
+    PUBLIC_DOMAIN = 'readthedocs.ngrok.io'
     PUBLIC_API_URL = f'http://{PRODUCTION_DOMAIN}'
 
     SLUMBER_API_HOST = 'http://web:8000'
@@ -144,8 +144,8 @@ class DockerBaseSettings(CommunityDevSettings):
     S3_BUILD_COMMANDS_STORAGE_BUCKET = 'builds'
     S3_BUILD_ENVIRONMENT_STORAGE_BUCKET = 'envs'
     S3_STATIC_STORAGE_BUCKET = 'static'
-    S3_STATIC_STORAGE_OVERRIDE_HOSTNAME = 'community.dev.readthedocs.io'
-    S3_MEDIA_STORAGE_OVERRIDE_HOSTNAME = 'community.dev.readthedocs.io'
+    S3_STATIC_STORAGE_OVERRIDE_HOSTNAME = 'readthedocs.ngrok.io'
+    S3_MEDIA_STORAGE_OVERRIDE_HOSTNAME = 'readthedocs.ngrok.io'
 
     AWS_AUTO_CREATE_BUCKET = True
     AWS_DEFAULT_ACL = 'public-read'
```

We should explain this somewhere in our https://docs.readthedocs.io/en/stable/development/standards.html guide and/or create a command that automates this process.

### PR DESCRIPTION
**Pull request by thinh241819**
Updated install documentation with information regarding using Ngrok with a locally running instance on Docker.

Added a section "Running Ngrok" into "Working with Docker Compose"

Closes #7982

### CODE REVIEW

**Comment by humitos** [comment]
Hi! Thanks for opening this PR. How hard it would be to automate these changes into a command like `inv docker.up --ngrok` (note that I'm passing `--ngrok` here expecting these changes to be done automatically)?

**Comment by thinh241819** [comment]
I read about the structure of the ```docker.up``` function and see that it is mostly passing parameters to ```cmd``` variable and finally running that ```cmd```. 

The way I plan to implement the command is that I open the files that needed to be changed, then search for the lines and change them. Such a function would break the existing structure of ```docker.up``` function, so I put it as a separated function called ```ngroksetup``` in the ```l10n``` namespace

I would do some more research on this to see if there are other methods and would love to hear more instructions if you have them.

**Comment by thinh241819** [comment]
> Hi! Thanks for opening this PR. How hard it would be to automate these changes into a command like `inv docker.up --ngrok` (note that I'm passing `--ngrok` here expecting these changes to be done automatically)?

Hi @humitos. I read about the structure of the ```docker.up``` function and see that it is mostly passing parameters to ```cmd``` variable and finally running that ```cmd```. 

The way I plan to implement the command is that I open the files that needed to be changed, then search for the lines and change them. Such a function would break the existing structure of ```docker.up``` function, so I put it as a separated function called ```ngroksetup``` in the ```l10n``` namespace

I would do some more research on this to see if there are other methods and would love to hear more instructions if you have them.

**Comment by ShivanS93** [comment]
just needs to be remerged. Lol trailing whitspace failed on pre-commit.

**Pull request closed without merging**
