### PR TITLE
Notifications: email about `DONT_SHALLOW_CLONE` deprecated feature flag

### PR DESCRIPTION
**Pull request by humitos**
This PR prepare an email notification to be sent to users with projects using this feature flag. We use a similar pattern than the one used for the deprecation of the configuration file: 1 email per user listing all their projects affected [^1].

There are set of different changes in this PR (each set has it's own commit to make it easier to review):

* Expand the `contact_owners.py` management command
  - Follow the convention we have in other notifications regarding the context: us `production_uri` instead of `domain`
  - Add all the `projects` for a particular user to the context, so we can show actions specific to those projects
  - Use the internal `get_context_data()` and `extra_context=` to follow the pattern stablished for the `Notification` class.
* Add a template filter to check if a `Project` has a feature flag or not
* Write an initial email to be reviewed by the team

### Preview

Screenshot_2023-06-22_18-19-48

[^1]: I'd like to standardize this pattern in a generic way somehow, but I don't want to deviate too much right, so I made some small changes to allow me to do this in a simple way for now.

Related: #9779

### CODE REVIEW

**Comment by stsewd** [comment]
I think we should stop trying to adapt the command each time we want to send an email, and just call it from a script, as mentioned in https://github.com/readthedocs/readthedocs.org/pull/9882#issuecomment-1385838640.

**Comment by humitos** [comment]
Is expanding the script a problem? This PR does not do make breaking changes on the script; it just add functionality. This also helps to keep the script maintained and working when we need it.

**Comment by stsewd** [comment]
This is injecting all projects by default in the context, and adding a filter, which shouldn't be required for all types of emails/notifications. This can be just a custom context function, with all the proper projects already filtered.

**Comment by ericholscher** [comment]
I tend to agree... it seems like if we're not going to be sending these emails in an automated fashion, just having a script that we run to send them is a lot simpler, and doesn't require a deploy or code changes. It would make it much easier to iteratively send notifications to each of our feature flag users in a pretty quick way, and we could keep the scripts in VCS if we wanted to review/version control them. I don't feel super strongly, though, but I do see how requiring deploys makes it more annoying to ship these notifications.

**Comment by humitos** [comment]
OK. I'm closing this PR and I will create a different script. I opened https://github.com/readthedocs/readthedocs.org/pull/10470 with the changes required to follow the conventions we have and keep consistency.

**Pull request closed without merging**
