### PR TITLE
Simplify docker image

### PR DESCRIPTION
**Pull request by stsewd**
- We don't need all those files in the context
- WORKDIR creates all missing directories

Also, since we are not using this image for deploy, we could just skip the installation of requirements.txt, that is done with when running with docker compose with `INIT=t`

### CODE REVIEW

**Comment by humitos** [comment]
I think I'm fine with these changes. Although, I need to pull down the branch and re-build the image to be 100% sure.

>     * WORKDIR creates all missing directories

All the paths from docker-compose are based on where the code is clone, etc. So, if we remove the workdir we will probably end up with files located in different places and we will need to update them as well.

> Also, since we are not using this image for deploy, we could just skip the installation of requirements.txt, that is done with when running with docker compose with `INIT=t`

I prefer to have everything that it's known to be installed already in the image. It speed up things after removing the container with `down`. Otherwise, each time you do a `down` and then an `up` you need to re-install all the requirements again (--init is not needed in that case).

**Comment by stsewd** [comment]
> All the paths from docker-compose are based on where the code is clone, etc. So, if we remove the workdir we will probably end up with files located in different places and we will need to update them as well.

Docker compose uses the mounted directories actually

> I prefer to have everything that it's known to be installed already in the image. It speed up things after removing the container with down. Otherwise, each time you do a down and then an up you need to re-install all the requirements again (--init is not needed in that case).

That's why you should use start and stop instead of up/down

**Comment by humitos** [comment]
> Docker compose uses the mounted directories actually

Good point. Did you test this Dockerfile and built it properly with current `master`?

**Comment by stsewd** [comment]
> Good point. Did you test this Dockerfile and built it properly with current master?

Yeah

**Pull request merged**
