### PR TITLE
Subscriptions: avoid double deletion

### PR DESCRIPTION
**Pull request by stsewd**
Subscription is set to cascade delete
when an organization is deleted,
with this additional signal
we are cancelling the subscription twice,
and stripe is given an error.

### CODE REVIEW

**Review by humitos — COMMENTED** [review]
Where are we canceling the subscription on Stripe when the organization is deleted?

**Comment by stsewd** [comment]
@humitos https://github.com/readthedocs/readthedocs.org/blob/97ee9ba65c0d995fe65317160d4ad32e3bb89065/readthedocs/subscriptions/signals.py#L16-L17

**Comment by stsewd** [comment]
> If the Subscription is set to CASCADE, it won't trigger Django signals and then 

It will, when you delete an org, all their related objects will be deleted as you manually called `.delete()` on each one, that's why tests are passing.

**Comment by humitos** [comment]
@stsewd 

> It will, when you delete an org, all their related objects will be deleted as you manually called `.delete()` on each one, that's why tests are passing.

I think you are confused about this, `.delete()` is not called. Take a look at the Django documentation https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.CASCADE

However, the last sentence says,

> but the [pre_delete](https://docs.djangoproject.com/en/4.0/ref/signals/#django.db.models.signals.pre_delete) and [post_delete](https://docs.djangoproject.com/en/4.0/ref/signals/#django.db.models.signals.post_delete) signals are sent for all deleted objects

I understand that "for all deleted objects" only applies to the original objects, not the CASCADEd ones because Django does not really know what are those objects, so it can't trigger those signals for them.

I want to be 100% sure that we are understanding exactly how it works because I want to prevent any issues with the subscriptions that are hard to detect and affect directly our income and onboarding UX + support time, etc

**Comment by stsewd** [comment]
@humitos 

> When Django deletes an object, by default it emulates the behavior of the SQL constraint ON DELETE CASCADE – in other words, any objects which had foreign keys pointing at the object to be deleted will be deleted along with it. For example:

https://docs.djangoproject.com/en/4.0/topics/db/queries/#topics-db-queries-delete

In any way, we have tests for this at .com (se also `#1436` on .com)

**Comment by humitos** [comment]
It would be good to update this PR to a mergeable state since we are still hitting this issue.

**Pull request merged**
