### PR TITLE
Footer: remove jsonp call

### PR DESCRIPTION
**Pull request by stsewd**
Use normal json instead,
we don't have problems with CORS anymore and this allow us to cache the
footer.

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
Makes sense to me 👍

**Review by davidfischer — APPROVED** [review]
This will work as long as the `proxied_api_host` is the same as the host. Otherwise it won't work. Also, you can remove `crossDomain: true,` I believe.

**Comment by ericholscher** [comment]
We should probably just change the function name on the jsonp call to be consistent tho, and that will solve this issue with fewer changes. 👍

**Review by ericholscher — APPROVED** [review]
This looks like a better approach, and protects use cases that aren't doing proxied API. I wonder if the analytics endpoint should use jsonp for consistency?

**Comment by stsewd** [comment]
> I wonder if the analytics endpoint should use jsonp for consistency?

The way I see it, jsonp is just a hack around CORS, I think new endpoints should  use CORS rules to fix that.
We already do something like that here https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/core/signals.py#L36-L36

**Pull request merged**
