### PR TITLE
Rebase remote-repository-normalization branch to master and Fix merge conflict

### PR DESCRIPTION
**Pull request by saadmk11**

### CODE REVIEW

**Comment by humitos** [comment]
Isn't it easier to merge `master` into `remote-repository-normalization` instead?

**Comment by saadmk11** [comment]
> Isn't it easier to merge `master` into `remote-repository-normalization` instead?

@humitos I did rebase here. should I merge master to remote-repository-normalization instead?

**Comment by humitos** [comment]
I think it's easier to do and to review as well. Currently, this PR has 85 files changes that were already reviewed in other PRs. I think that doing a merge will only show relevant changes here.

**Comment by saadmk11** [comment]
closing this in favour of https://github.com/readthedocs/readthedocs.org/pull/7795

**Pull request closed without merging**
