### PR TITLE
Add beta version of doc diff library for testing

### PR DESCRIPTION
**Pull request by agjohnson**
Very slim chance this works as expected

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--9546.org.readthedocs.build/en/9546/

- Developer's documentation (`dev`): https://dev--9546.org.readthedocs.build/en/9546/

### CODE REVIEW

**Comment by agjohnson** [comment]
Yeah, CORS error, about what I expected.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.readthedocs.io/en/latest/versions.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Page that should have a diff: https://docs--9546.org.readthedocs.build/en/9546/versions.html

**Comment by humitos** [comment]
This works pretty nice! (I had to disable the CORS restriction in my browser, tho)

Screenshot_2022-08-24_19-18-48

I noticed that it detected a weird change in the table, tho. It seems that table was not changed in the PR.

Screenshot_2022-08-24_19-19-20

**Comment by agjohnson** [comment]
> I noticed that it detected a weird change in the table, tho

That is odd, the HTML is identical :thinking:

**Comment by agjohnson** [comment]
I opened https://github.com/readthedocs/doc-diff/issues/5 to discuss CORS and authentication mitigation at a broad level.

**Comment by ericholscher** [comment]
This is wonderful! Excited to figure out the CORS issue, and have some of this magic in our PR's 🎉

**Comment by humitos** [comment]
@stsewd how hard would be to enable CORS for this particular case? I'd love to see this PR merged and in action for our repository at least.

**Comment by stsewd** [comment]
@humitos there is an issue related to this at https://github.com/readthedocs/readthedocs-corporate/issues/1482. We should be safe to allow cross site requests on .org, since everything is public, and we don't use cookies on the docs domains (we could even restrict this for domains that are valid on .org only).

**Comment by ericholscher** [comment]
We could use a CORS proxy for this:  https://cors.writethedocs.workers.dev/corsproxy/?apiurl=https://docs.readthedocs.io/en/stable/

**Comment by agjohnson** [comment]
image

**Comment by ericholscher** [comment]
Fancy :)

**Comment by humitos** [comment]
It works! 💪🏼

**Comment by agjohnson** [comment]
Note, what we added was a hack. I'd wait to merge this until we have a proxy maintained on the RTD side.

**Comment by humitos** [comment]
OK, this is looking good so far:

Screenshot_2023-03-07_10-43-30

I'm going to merge it and we can continue from there.

**Review by humitos — APPROVED** [review]

**Comment by ericholscher** [comment]
Nice.

**Pull request merged**
