### PR TITLE
Analytics: make sure there is only one record with version=None

### PR DESCRIPTION
**Pull request by stsewd**
By default Postgres doesn't consider two null values equal,
so you can create a duplicated record with a null value,
even if it has a unique constraint.

Postgres does provide a way to change that (`NULLS NOT DISTINCT`).

https://www.postgresql.org/docs/15/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS

But to use it from Django, we would need to execute a raw sql
expression.

So, another approach to avoid executing a raw sql is to create two constraints,
one with the normal constraint of unique fields,
and another one that doesn't include the optional field,
but it includes a condition (version=None).

Note that we are using get_or_create,
which does properly check if there is already a version
with `None`, but if more than on request are executed at the same time,
then get_or_create will end up inserting the record more than once
since the unique constraint with `None` wasn't enforced at the db level.

Closes https://github.com/readthedocs/readthedocs.org/issues/9316

### How to deploy this

- Deploy as usual (don't run migrations before releasing the webs!)
- Create the `DISABLE_PAGEVIEWS` feature with future/past projects set to true.
- Run the migrations (0004 and 0005)
- Delete the `DISABLE_PAGEVIEWS` feature flag

### CODE REVIEW

**Comment by stsewd** [comment]
I realized we will need a data migration to merge the duplicate entries, I'm writing one now.

**Comment by stsewd** [comment]
> I realized we will need a data migration to merge the duplicate entries, I'm writing one now.

We could also just let them be, since we don't insert that same record after a day has passed, and showing the number of page views does work.
There are 776 duplicate records on .com.

The data migration would be:

```py
def forwards_func(apps, schema_editor):
    """Merge records with duplicated entries."""
    PageView = apps.get_model("analytics", "PageView")
    queryset = (
        PageView.objects
        .filter(version=None)
        .values('project', 'date', 'path', 'status')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for result in queryset:
        count = result.pop('count')
        duplicates = list(PageView.objects.filter(
            **result,
            version=None,
        ))
        if duplicates:
            pageview = duplicates[0]
            pageview.view_count = count
            pageview.save()
            PageView.objects.filter(id__in=[pv.id for pv in duplicates[1:]]).delete()
```

**Comment by stsewd** [comment]
But, looks like if there are duplicate records, we can't create the new index :/, so we do need the data migration. But, we also need to disable page views momentary, before running the data migration, so there is no new invalid data created in the meantime.

**Review by ericholscher — APPROVED** [review]
This seems good. I don't love creating a new large index on this table as it will take up more space, but seems like a reasonable approach. 

Definitely note this on the release card so that we do the migrations properly.

**Pull request merged**
