### PR TITLE
Add READTHEDOCS_LANGUAGE to the environment during builds

### PR DESCRIPTION
**Pull request by ericholscher**
This was requested by a user since they can't get it via conf.py,
because we inject our logic after their conf.py data.

### CODE REVIEW

**Comment by stsewd** [comment]
https://github.com/readthedocs/readthedocs.org/blob/master/docs/builds.rst#build-environment should be updated

**Comment by ericholscher** [comment]
Yep, was just working on that :)

**Comment by akien-mga** [comment]
> No more ascii char tables :D

TIL about the `csv-table` directive, that's going to be quite useful :D

**Comment by akien-mga** [comment]
Confirmed working after #5951, thanks a lot!

**Pull request merged**
