### PR TITLE
Search: remove old endpoint

### PR DESCRIPTION
**Pull request by stsewd**

### CODE REVIEW

**Review by humitos — APPROVED** [review]
I'm not have the full context to do a good review of this, but as far as I can tell, the removal of the old endpoint looks good.

Aren't there any test cases for this endpoint that need to be removed?

**Comment by stsewd** [comment]
> Aren't there any test cases for this endpoint that need to be removed?

Tests were changed to use the new endpoint when it was implemented. But I'll wait one more week before fulling removing this, but all docs should be pointing at the new endpoint by now.

**Comment by humitos** [comment]
Did we already contact people using this endpoint and they already migrated to the new one?

**Comment by stsewd** [comment]
I have contacted all of them already, we decided we shouldn't wait they were using something custom or outside rtd as we never documented this api.

**Review by ericholscher — APPROVED** [review]
I'd like to find a better way of deprecating this for users. Is it easy to return a message/page on that URL linking to the new API? Should we 302 it and then let it fail on the JSON response differences? Not sure if there's a great answer here, but might be a more user-friendly deprecation path.

**Comment by stsewd** [comment]
Do you mean something like this at the django or nginx level?

**Pull request merged**
