### PR TITLE
Content-type header added to webhook notifications

### PR DESCRIPTION
**Pull request by saadmk11**
closes: https://github.com/readthedocs/readthedocs.org/issues/6631

### CODE REVIEW

**Comment by saadmk11** [comment]
@humitos Not quite sure why we should test the requests library here as it adds the `content-type` header automatically when `json` is passed but if we do I don't see any easy way to test the requests object without sending any request and doing some hacks.

**Comment by stsewd** [comment]
I think this may break compatibility. We were sending this as form-data. Maybe would be better to update the docs

**Comment by stsewd** [comment]
Actually, we don't send the dictionary, but a json as string.

**Comment by saadmk11** [comment]
I think 
`r = requests.post(url, data=json.dumps(payload))`
and
`r2= requests.post(url, json=payload)`

Does the same thing. just the second one adds the `content-type` header automatically and for the first one we need to add the header manually 


https://github.com/psf/requests/blob/a9906536ee971872e5031a0138d63fb4ea481511/requests/models.py#L463-L469

**Comment by humitos** [comment]
@saadmk11 I don't want to test requests. I want a way to prevent this to happen again to us. Basically, to be sure that we are sending that header. How will we notice that we are breaking this if we revert this commit?

**Comment by saadmk11** [comment]
@humitos Sure! Updated the PR :)

**Comment by jack1142** [comment]
Thanks for making the fix :)

**Pull request merged**
