### PR TITLE
Add error view for error handling and error view testing

### PR DESCRIPTION
**Pull request by agjohnson**
I was having trouble testing error views and templates locally and found
at some point we added a `/500` for testing the 500 error page. I
expanded on this to create a view that could emit any error status code
and relevant template. Afterwards, it seemed like we had a few redundant
views doing similar things, so I expanded the dashboard error handlers
to all use the same view as well.

Changes here are:

- When using the new dashboard, dashboard error templates are in the
  `/errors/dashboard/` template path. There will be a duplicate set of
  templates for Proxito errors and documentation errors, in
  `/errors/proxito/` eventually.
- This swaps out the URL `handler500`, and defines the missing handlers
  in the URL module. Mostly, this loads these error templates from a
  more structured path instead of top level `/404.html` templates.
- Adds a debug view/URL for testing arbitrary error views/templates in
  debug mode.

This does not touch proxito error pages yet.

- Refs https://github.com/readthedocs/ext-theme/issues/295

### CODE REVIEW

**Review by humitos — APPROVED** [review]
This is great!

**Comment by agjohnson** [comment]
The test failure is due to the default handler giving up on loading a missing template:

https://github.com/django/django/blob/main/django/views/defaults.py#L139-L150

I'll see about adding this or just add a 403 template, it probably doesn't matter as we're already not giving a templated response in these views.

**Comment by agjohnson** [comment]
I did indeed just symlink the 401 to 403 template for now. I'm guessing if anyone is replicating the test case responses in real life, they are just getting the default, empty, Django 403 reponse. The 401 template wasn't entirely a great fit, but it's good enough because of all of this.

Same on https://github.com/readthedocs/readthedocs-corporate/pull/1767

**Comment by agjohnson** [comment]
Docs failures are unrelated, I'll merge this now.

**Comment by humitos** [comment]
This is why the fancy 404 pages weren't working on production yet? 😄

**Pull request merged**
