### PR TITLE
Try out codeowners

### PR DESCRIPTION
**Pull request by agjohnson**
I just learned about this feature. We can apparently default who to
delegate review to.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

### CODE REVIEW

**Comment by stsewd** [comment]
Think we can try to scope this down a little, like `readthedocs/ @readthedocs/backend`. I mean, I'm fine with asking review on any other file, but you and Eric are on those groups as well.

**Comment by agjohnson** [comment]
Makes sense, I'll try default to backend for everything to test then. I could see us getting pretty granular with review if this works well.

**Review by humitos — APPROVED** [review]
Makes sense. We could add other teams as well, like `docs/* @readthedocs/advocacy` for example. I read that this is just a test for now, but I think it will work.

**Comment by agjohnson** [comment]
Or `dockerfiles/*     @humitos` :wink:

**Comment by humitos** [comment]
Sold!

**Pull request merged**
