### PR TITLE
Don't compare inactive or non build versions

### PR DESCRIPTION
**Pull request by stsewd**
This is a better approach for https://github.com/readthedocs/readthedocs.org/pull/6353

### CODE REVIEW

**Comment by humitos** [comment]
I'm not sure to understand how this PR works. It's linked to the issue "List only built versions on the footer" (#6137) but from what I understand here, it just does not consider `build=False` and `active=False` when comparing versions to know which one is the highest.

Although, I'm not sure why or where this will affect to the versions shown in the footer.

**Comment by humitos** [comment]
Is this "hidden feature" (https://github.com/readthedocs/readthedocs.org/issues/6137#issuecomment-550370630) still possible after this PR is merged?

**Comment by stsewd** [comment]
@humitos got confused where this is used. This is only used to show the banner `You are seeing an old version, there is a new one here...` To get the urls from the footer we call `get_subdomain_url` which calls to resolve directly.

**Comment by stsewd** [comment]
@humitos 

https://github.com/readthedocs/readthedocs.org/blob/2f97d8b9254fb89d227d05ac9abb0750d36df9b2/readthedocs/api/v2/templates/restapi/footer.html#L44-L44

**Pull request merged**
