### PR TITLE
Minor refactor of Private Python packages page

### PR DESCRIPTION
**Pull request by plaindocs**
to improve readability and clarity.

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--11395.org.readthedocs.build/en/11395/

- Developer's documentation (`dev`): https://dev--11395.org.readthedocs.build/en/11395/

### CODE REVIEW

**Review by humitos — COMMENTED** [review]
Looks good to me! I think we are ready to remove the "draft" status and move forward with it 👍🏼

**Comment by plaindocs** [comment]
Thanks for the reminder @humitos

**Review by humitos — APPROVED** [review]

**Review by humitos — APPROVED** [review]
Great! Thanks for jumping into this 💯

**Comment by humitos** [comment]
He, look at that! Double _Approved_!

**Pull request merged**
