### PR TITLE
Docs: Configuration file pages as explanation and reference (Diátaxis)

### PR DESCRIPTION
**Pull request by benjaoming**
**Not ready for review**

Depends on: https://github.com/readthedocs/readthedocs.org/pull/10071

This flags changes that are incoming

Refs: #9746 
Fixes: #8648

---
:books: Documentation previews :books:

- User's documentation (`docs`): https://docs--9921.org.readthedocs.build/en/9921/

- Developer's documentation (`dev`): https://dev--9921.org.readthedocs.build/en/9921/

### CODE REVIEW

**Comment by benjaoming** [comment]
!! Pay attention to some .py files being changed in this PR (probably the target branch is outdated)

**Comment by benjaoming** [comment]
A minimal change can be viewed in https://github.com/benjaoming/readthedocs.org/pull/6

**Comment by benjaoming** [comment]
This PR is ready for review with a bigger disclaimer, namely that it's currently easier to review here: https://github.com/benjaoming/readthedocs.org/pull/6/files

**Comment by ericholscher** [comment]
> This PR is ready for review with a bigger disclaimer, namely that it's currently easier to review here: https://github.com/benjaoming/readthedocs.org/pull/6/files

I'm confused... what are the PR's on your fork for? This isn't a workflow we generally use.

**Comment by benjaoming** [comment]
> I'm confused... what are the PR's on your fork for? This isn't a workflow we generally use.

I stopped using this workflow some months ago. But these changes are older. I wanted to have this PR point to a different base branch, but since the base branch is in my fork, it got necessary.

Pretty good argument to avoid forked repos in a workflow.. chained PRs aren't possible.

> This PR has a bunch of additional changes in it from other PR's as well?

Yes, this PR has been around way too long :/ It now contains all of #10071 - I fail to recall the reasoning.

I could move all changes over in #10071, but this PR is already _too long_ for a nice a simple review process.

**Comment by ericholscher** [comment]
I'd recommend breaking the PRs up into discrete changes. I can't really track what is happening between them. Does it make sense to try to review and merge #10071 first, and then look at this as a diff on top of that?

**Comment by benjaoming** [comment]
> Does it make sense to try to review and merge https://github.com/readthedocs/readthedocs.org/pull/10071 first, and then look at this as a diff on top of that?

Yes, I think so.

#10071 is a bit hefty, but we'll have to wrestle it sooner or later... better to wrestle it sooner because it has this PR stacked on top.

Once #10071 is in, I can merge/rebase this PR branch so it gets simpler to review.

**Comment by ericholscher** [comment]
We could also just push this branch to the main RTD repo, and chain it on top of #10071? But I think #10071 is gonna change a lot from here, and lead to lots of conflicts, so we should definitely pause this one until that one is done, then reevaluate.

**Comment by benjaoming** [comment]
I definitely did _something_ in this PR that requires https://github.com/readthedocs/readthedocs.org/pull/10071 because I explicitly merged it in at some point.

I'll mark it as blocked for now :+1:

**Comment by benjaoming** [comment]
I should also mention that there is another similar change chained on https://github.com/readthedocs/readthedocs.org/pull/10071 :

https://github.com/benjaoming/readthedocs.org/pull/3/files

**Comment by benjaoming** [comment]
Cut out and proposed here: https://github.com/readthedocs/readthedocs.org/pull/10416

**Pull request closed without merging**
