### PR TITLE
API v2: allow listing when using private repos

### PR DESCRIPTION
**Pull request by stsewd**

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
Looks good to me 👍

**Review by humitos — COMMENTED** [review]
I'm fine merging this if _it's required_ for .com users. However, I'd like to keep consistency with .org if possible.

I understand that listing all the repositories the user has access to won't be a problem for our servers, but: do we want to add another difference between .org and .com if it's not required?

**Comment by stsewd** [comment]
> do we want to add another difference between .org and .com if it's not required?

We are possibly breaking user's usage of api v2 in commercial, and asking them to use apiv3 without any previous  deprecation warnings. And hopefully we won't be touching api v2 anymore and deprecate it for good.

**Comment by ericholscher** [comment]
I don't think we got any user feedback on this, but I think it's good to merge it just in case, to not break someone's workflow.

**Comment by stsewd** [comment]
> Though we can perhaps just wait until we get a support request, and then hotfix it?

Think we can just include it now, so we don't have to re-deploy later. But true, we haven't had support requests for this.

**Comment by ericholscher** [comment]
Yea, I'm guessing nobody is using it, but I'd like to not break it, so I guess let's just ship it and avoid a user having a bad experience, if they are.

**Pull request merged**
