### PR TITLE
Fix footer

### PR DESCRIPTION
**Pull request by stsewd**
It wasn't rendering correctly

### CODE REVIEW

**Comment by ericholscher** [comment]
Is there a way to check for this in tests? Feels like something we should be finding automatically.

**Comment by stsewd** [comment]
we have tests that hit this template, but it wasn't raising a syntax error, it was just rendering it wrong :/

**Comment by ericholscher** [comment]
> we have tests that hit this template, but it wasn't raising a syntax error, it was just rendering it wrong :/

How can we make the test raise a syntax error?

**Comment by ericholscher** [comment]
Opened https://github.com/readthedocs/readthedocs.org/issues/6290

**Pull request merged**
